// CompTIA Security+ SY0-701 acronym list for the rapid-fire drill.
// {a: acronym, full: expansion, note: exam context, ch: chapter number}
window.ACRONYMS = [
 // ----- Chapter 1: Today's Security Professional -----
 {a:"CIA", full:"Confidentiality, Integrity, Availability", note:"The three core security objectives (the CIA triad).", ch:1},
 {a:"DAD", full:"Disclosure, Alteration, Denial", note:"The opposite of CIA — the three key threats.", ch:1},
 {a:"AAA", full:"Authentication, Authorization, and Accounting", note:"Prove identity, grant rights, then log activity.", ch:1},
 {a:"DLP", full:"Data Loss Prevention", note:"Blocks exfiltration of sensitive data (host or network based).", ch:1},
 {a:"NDA", full:"Non-Disclosure Agreement", note:"Contract to keep shared information confidential.", ch:16},

 // ----- Chapter 2: Cybersecurity Threat Landscape -----
 {a:"APT", full:"Advanced Persistent Threat", note:"Stealthy, well-funded attacker (often nation-state).", ch:2},
 {a:"OSINT", full:"Open-Source Intelligence", note:"Threat intel gathered from public sources.", ch:2},
 {a:"TTP", full:"Tactics, Techniques, and Procedures", note:"How a threat actor operates; basis of threat profiling.", ch:2},
 {a:"IoC", full:"Indicator of Compromise", note:"Forensic evidence a system may be breached.", ch:2},
 {a:"STIX", full:"Structured Threat Information eXpression", note:"Standard FORMAT for sharing threat intel.", ch:2},
 {a:"TAXII", full:"Trusted Automated eXchange of Indicator Information", note:"PROTOCOL for transporting STIX threat data.", ch:2},
 {a:"AIS", full:"Automated Indicator Sharing", note:"CISA program for real-time threat indicator exchange.", ch:2},
 {a:"ISAC", full:"Information Sharing and Analysis Center", note:"Industry group that shares threat intelligence.", ch:2},
 {a:"AI", full:"Artificial Intelligence", note:"Used by both defenders and attackers; expands attack surface.", ch:2},
 {a:"ML", full:"Machine Learning", note:"Subset of AI; used in detection and by adversaries.", ch:2},
 {a:"MSP", full:"Managed Service Provider", note:"Outsourced IT vendor; a supply-chain risk vector.", ch:2},
 {a:"USB", full:"Universal Serial Bus", note:"Removable media — a physical threat vector for malware.", ch:2},

 // ----- Chapter 3: Malicious Code -----
 {a:"RAT", full:"Remote Access Trojan", note:"Trojan giving an attacker remote control of a host.", ch:3},
 {a:"C2", full:"Command and Control", note:"Infrastructure an attacker uses to control bots/malware.", ch:3},
 {a:"P2P", full:"Peer-to-Peer", note:"Decentralized model abused by botnets for resilience.", ch:3},
 {a:"MBR", full:"Master Boot Record", note:"Boot sector targeted by some viruses/bootkits.", ch:3},
 {a:"VBA", full:"Visual Basic for Applications", note:"Macro language abused to deliver macro viruses.", ch:3},

 // ----- Chapter 4: Social Engineering & Password Attacks -----
 {a:"BEC", full:"Business Email Compromise", note:"Impersonating an exec/vendor to trick payments or data.", ch:4},
 {a:"SPIM", full:"Spam over Instant Messaging", note:"Unsolicited messages pushed via IM platforms.", ch:4},
 {a:"OTP", full:"One-Time Password", note:"Single-use code; phishing targets it in real time.", ch:4},

 // ----- Chapter 5: Security Assessment & Testing -----
 {a:"CVE", full:"Common Vulnerabilities and Exposures", note:"Standard unique ID for each known vulnerability.", ch:5},
 {a:"CVSS", full:"Common Vulnerability Scoring System", note:"0–10 severity score for a vulnerability.", ch:5},
 {a:"SCAP", full:"Security Content Automation Protocol", note:"Standards suite (incl. CVE & CVSS) for automating vuln data.", ch:5},
 {a:"OVAL", full:"Open Vulnerability and Assessment Language", note:"SCAP component for describing system state/vulns.", ch:5},

 // ----- Chapter 6: Application Security -----
 {a:"SDLC", full:"Software Development Life Cycle", note:"Process for building software (dev→test→staging→prod).", ch:6},
 {a:"SDK", full:"Software Development Kit", note:"Tools/libraries for building apps on a platform.", ch:6},
 {a:"API", full:"Application Programming Interface", note:"App-to-app interface; secure with auth & input validation.", ch:6},
 {a:"SQL", full:"Structured Query Language", note:"Database language abused via SQL injection (SQLi).", ch:6},
 {a:"SQLi", full:"SQL Injection", note:"Injecting malicious SQL via unvalidated input.", ch:6},
 {a:"XSS", full:"Cross-Site Scripting", note:"Injecting scripts that run in other users' browsers.", ch:6},
 {a:"CSRF", full:"Cross-Site Request Forgery", note:"Tricks a logged-in user's browser into unwanted requests.", ch:6},
 {a:"XSRF", full:"Cross-Site Request Forgery", note:"Alternate abbreviation for CSRF.", ch:6},
 {a:"SAST", full:"Static Application Security Testing", note:"Analyzes source code WITHOUT running it.", ch:6},
 {a:"DAST", full:"Dynamic Application Security Testing", note:"Tests the application WHILE it runs.", ch:6},
 {a:"ASLR", full:"Address Space Layout Randomization", note:"Randomizes memory to thwart buffer-overflow exploits.", ch:6},
 {a:"DEP", full:"Data Execution Prevention", note:"Marks memory non-executable to stop injected code.", ch:6},
 {a:"DLL", full:"Dynamic Link Library", note:"Shared code library abused via DLL injection.", ch:6},
 {a:"CI/CD", full:"Continuous Integration / Continuous Deployment", note:"Automated build/test/deploy pipeline; embeds security testing.", ch:6},
 {a:"XML", full:"Extensible Markup Language", note:"Data format; vulnerable to XXE injection.", ch:6},
 {a:"SOAP", full:"Simple Object Access Protocol", note:"XML-based web service protocol.", ch:6},
 {a:"TOCTOU", full:"Time-of-Check to Time-of-Use", note:"Race-condition flaw exploited between check and use.", ch:6},

 // ----- Chapter 7: Cryptography & the PKI -----
 {a:"PKI", full:"Public Key Infrastructure", note:"System of CAs/certs that lets parties trust public keys.", ch:7},
 {a:"CA", full:"Certificate Authority", note:"Trusted entity that issues and signs digital certificates.", ch:7},
 {a:"RA", full:"Registration Authority", note:"Verifies identity/requests on behalf of a CA.", ch:7},
 {a:"CSR", full:"Certificate Signing Request", note:"Request (with public key) sent to a CA for a cert.", ch:7},
 {a:"CRL", full:"Certificate Revocation List", note:"Published list of revoked certificates.", ch:7},
 {a:"OCSP", full:"Online Certificate Status Protocol", note:"Real-time query of a single cert's revocation status.", ch:7},
 {a:"AES", full:"Advanced Encryption Standard", note:"Modern symmetric block cipher (128/192/256-bit).", ch:7},
 {a:"DES", full:"Data Encryption Standard", note:"Obsolete 56-bit symmetric cipher; insecure.", ch:7},
 {a:"3DES", full:"Triple DES", note:"Applies DES three times; legacy, being retired.", ch:7},
 {a:"RSA", full:"Rivest-Shamir-Adleman", note:"Asymmetric algorithm based on factoring large primes.", ch:7},
 {a:"ECC", full:"Elliptic Curve Cryptography", note:"Strong asymmetric crypto with small keys (good for mobile/IoT).", ch:7},
 {a:"DH", full:"Diffie-Hellman", note:"Key-exchange algorithm to agree on a shared secret.", ch:7},
 {a:"DHE", full:"Diffie-Hellman Ephemeral", note:"DH with one-time keys → perfect forward secrecy.", ch:7},
 {a:"ECDHE", full:"Elliptic Curve Diffie-Hellman Ephemeral", note:"Ephemeral DH over elliptic curves; PFS, efficient.", ch:7},
 {a:"DSA", full:"Digital Signature Algorithm", note:"Asymmetric algorithm used for digital signatures.", ch:7},
 {a:"SHA", full:"Secure Hash Algorithm", note:"Hashing family; SHA-2/SHA-3 strong, SHA-1 broken.", ch:7},
 {a:"MD5", full:"Message Digest 5", note:"128-bit hash; broken (collisions), avoid for security.", ch:7},
 {a:"HMAC", full:"Hash-based Message Authentication Code", note:"Hash + secret key → integrity AND authentication.", ch:7},
 {a:"IV", full:"Initialization Vector", note:"Random value making encryption outputs unique.", ch:7},
 {a:"PFS", full:"Perfect Forward Secrecy", note:"Ephemeral keys so past sessions stay safe if a key leaks.", ch:7},
 {a:"PBKDF2", full:"Password-Based Key Derivation Function 2", note:"Key-stretching to slow password cracking.", ch:7},
 {a:"HSM", full:"Hardware Security Module", note:"Dedicated device for generating/storing keys at scale.", ch:7},
 {a:"KEK", full:"Key Encryption Key", note:"A key used to encrypt other keys.", ch:7},
 {a:"PGP", full:"Pretty Good Privacy", note:"Encryption for email/files using a web of trust.", ch:7},
 {a:"GPG", full:"GNU Privacy Guard", note:"Open-source implementation of the OpenPGP standard.", ch:7},
 {a:"S/MIME", full:"Secure/Multipurpose Internet Mail Extensions", note:"Encrypts and signs email using certificates.", ch:7},
 {a:"PEM", full:"Privacy Enhanced Mail", note:"Base64 certificate/key file format.", ch:7},
 {a:"PKCS", full:"Public Key Cryptography Standards", note:"Standards for key/cert formats (e.g., PKCS#12 = .p12/.pfx).", ch:7},
 {a:"TLS", full:"Transport Layer Security", note:"Encrypts data in transit; successor to SSL.", ch:7},
 {a:"SSL", full:"Secure Sockets Layer", note:"Deprecated predecessor to TLS; insecure.", ch:7},
 {a:"GCM", full:"Galois/Counter Mode", note:"Authenticated cipher mode (encryption + integrity).", ch:7},
 {a:"CBC", full:"Cipher Block Chaining", note:"Block cipher mode where each block depends on the previous.", ch:7},
 {a:"ECB", full:"Electronic Codebook", note:"Weak cipher mode — identical blocks encrypt identically.", ch:7},

 // ----- Chapter 8: Identity & Access Management -----
 {a:"IAM", full:"Identity and Access Management", note:"Managing identities, authentication, and authorization.", ch:8},
 {a:"MFA", full:"Multifactor Authentication", note:"Two+ distinct factor types (know/have/are).", ch:8},
 {a:"SSO", full:"Single Sign-On", note:"Authenticate once, access many apps.", ch:8},
 {a:"SAML", full:"Security Assertion Markup Language", note:"XML standard for SSO and federation.", ch:8},
 {a:"LDAP", full:"Lightweight Directory Access Protocol", note:"Queries directory services (e.g., Active Directory).", ch:8},
 {a:"LDAPS", full:"LDAP Secure", note:"LDAP over TLS for encrypted directory queries.", ch:8},
 {a:"RADIUS", full:"Remote Authentication Dial-In User Service", note:"Open AAA protocol (UDP); encrypts only the password.", ch:8},
 {a:"TACACS+", full:"Terminal Access Controller Access-Control System Plus", note:"Cisco AAA (TCP); encrypts the whole payload, separates AAA.", ch:8},
 {a:"OAuth", full:"Open Authorization", note:"Framework to delegate limited access (authorization).", ch:8},
 {a:"OIDC", full:"OpenID Connect", note:"Authentication layer built on OAuth 2.0.", ch:8},
 {a:"RBAC", full:"Role-Based Access Control", note:"Access granted by job role (also: Rule-Based AC).", ch:8},
 {a:"ABAC", full:"Attribute-Based Access Control", note:"Access decided by attributes (user, resource, context).", ch:8},
 {a:"MAC", full:"Mandatory Access Control", note:"System enforces access via labels/clearances (also Media/Message AC).", ch:8},
 {a:"DAC", full:"Discretionary Access Control", note:"Data owner decides who gets access.", ch:8},
 {a:"PAM", full:"Privileged Access Management", note:"Controls/monitors admin accounts (JIT, vaulting).", ch:8},
 {a:"TOTP", full:"Time-based One-Time Password", note:"Code that changes every ~30s (authenticator apps).", ch:8},
 {a:"HOTP", full:"HMAC-based One-Time Password", note:"Counter/event-based one-time password.", ch:8},
 {a:"FAR", full:"False Acceptance Rate", note:"Biometrics: wrong person accepted (security risk).", ch:8},
 {a:"FRR", full:"False Rejection Rate", note:"Biometrics: legit person rejected (usability issue).", ch:8},
 {a:"CER", full:"Crossover Error Rate", note:"Where FAR=FRR; lower = better biometric system.", ch:8},
 {a:"PAP", full:"Password Authentication Protocol", note:"Legacy auth sending passwords in cleartext.", ch:8},
 {a:"CHAP", full:"Challenge-Handshake Authentication Protocol", note:"Auth via challenge/response without sending the password.", ch:8},
 {a:"NTLM", full:"New Technology LAN Manager", note:"Legacy Windows auth; vulnerable to relay/pass-the-hash.", ch:8},
 {a:"KDC", full:"Key Distribution Center", note:"Kerberos component that issues tickets.", ch:8},
 {a:"TGT", full:"Ticket Granting Ticket", note:"Kerberos ticket used to request service tickets.", ch:8},
 {a:"PIV", full:"Personal Identity Verification", note:"US gov smart card for authentication.", ch:8},
 {a:"CAC", full:"Common Access Card", note:"US DoD smart card for identity/authentication.", ch:8},
 {a:"IdP", full:"Identity Provider", note:"Service that authenticates users in a federation/SSO.", ch:8},

 // ----- Chapter 9: Resilience & Physical Security -----
 {a:"HA", full:"High Availability", note:"Designing systems for minimal downtime.", ch:9},
 {a:"RAID", full:"Redundant Array of Independent Disks", note:"Combines disks for redundancy and/or performance.", ch:9},
 {a:"RTO", full:"Recovery Time Objective", note:"How fast you must restore service after an outage.", ch:9},
 {a:"RPO", full:"Recovery Point Objective", note:"How much data loss is acceptable (drives backup frequency).", ch:9},
 {a:"MTBF", full:"Mean Time Between Failures", note:"Average uptime before a repairable system fails.", ch:9},
 {a:"MTTF", full:"Mean Time To Failure", note:"Average life of a non-repairable component.", ch:9},
 {a:"MTTR", full:"Mean Time To Repair", note:"Average time to fix and restore a failed system.", ch:9},
 {a:"UPS", full:"Uninterruptible Power Supply", note:"Battery providing immediate short-term backup power.", ch:9},
 {a:"PDU", full:"Power Distribution Unit", note:"Distributes power to rack equipment (also Protocol Data Unit).", ch:9},
 {a:"HVAC", full:"Heating, Ventilation, and Air Conditioning", note:"Environmental control for data centers.", ch:9},
 {a:"CCTV", full:"Closed-Circuit Television", note:"Surveillance cameras — a detective/deterrent control.", ch:9},
 {a:"RFID", full:"Radio Frequency Identification", note:"Wireless tags (badges); can be cloned/skimmed.", ch:9},
 {a:"BCP", full:"Business Continuity Plan", note:"Keeps the business running during/after a disruption.", ch:9},
 {a:"COOP", full:"Continuity of Operations Planning", note:"Ensuring essential functions continue during a disaster.", ch:9},

 // ----- Chapter 10: Cloud & Virtualization Security -----
 {a:"IaaS", full:"Infrastructure as a Service", note:"Cloud raw compute/storage/network (you manage OS up).", ch:10},
 {a:"PaaS", full:"Platform as a Service", note:"Cloud platform to run your own apps.", ch:10},
 {a:"SaaS", full:"Software as a Service", note:"Fully managed cloud application (e.g., M365).", ch:10},
 {a:"XaaS", full:"Anything as a Service", note:"Umbrella term for cloud service models.", ch:10},
 {a:"CASB", full:"Cloud Access Security Broker", note:"Policy enforcement point between users and cloud apps.", ch:10},
 {a:"CSP", full:"Cloud Service Provider", note:"Company delivering cloud services (AWS/Azure/GCP).", ch:10},
 {a:"VM", full:"Virtual Machine", note:"Software emulation of a computer on a hypervisor.", ch:10},
 {a:"VPC", full:"Virtual Private Cloud", note:"Isolated private network within a public cloud.", ch:10},
 {a:"VDI", full:"Virtual Desktop Infrastructure", note:"Hosting desktops on central servers.", ch:10},
 {a:"IaC", full:"Infrastructure as Code", note:"Provisioning infrastructure via version-controlled config.", ch:10},
 {a:"SDN", full:"Software-Defined Networking", note:"Separates network control plane from data plane.", ch:10},

 // ----- Chapter 11: Endpoint Security -----
 {a:"EDR", full:"Endpoint Detection and Response", note:"Monitors endpoints for threats; enables response.", ch:11},
 {a:"XDR", full:"Extended Detection and Response", note:"Correlates detection across endpoint, network, cloud, etc.", ch:11},
 {a:"AV", full:"Antivirus", note:"Signature-based malware detection.", ch:11},
 {a:"HIDS", full:"Host-based Intrusion Detection System", note:"Detects malicious activity on a single host.", ch:11},
 {a:"HIPS", full:"Host-based Intrusion Prevention System", note:"Detects AND blocks attacks on a host.", ch:11},
 {a:"FDE", full:"Full Disk Encryption", note:"Encrypts an entire drive at rest (e.g., BitLocker).", ch:11},
 {a:"SED", full:"Self-Encrypting Drive", note:"Drive with built-in hardware encryption.", ch:11},
 {a:"TPM", full:"Trusted Platform Module", note:"On-board chip storing keys; anchors boot integrity/FDE.", ch:11},
 {a:"UEFI", full:"Unified Extensible Firmware Interface", note:"Modern firmware/BIOS; enables Secure Boot.", ch:11},
 {a:"EFS", full:"Encrypting File System", note:"Windows file-level encryption.", ch:11},
 {a:"GPO", full:"Group Policy Object", note:"Windows setting that enforces config/security baselines.", ch:11},
 {a:"SCADA", full:"Supervisory Control and Data Acquisition", note:"Systems controlling industrial processes (ICS).", ch:11},
 {a:"ICS", full:"Industrial Control System", note:"Controls factories/utilities; needs special isolation.", ch:11},
 {a:"IoT", full:"Internet of Things", note:"Networked smart devices; weak default security.", ch:11},
 {a:"OT", full:"Operational Technology", note:"Hardware/software controlling physical processes.", ch:11},
 {a:"RTOS", full:"Real-Time Operating System", note:"OS for time-critical embedded systems.", ch:11},
 {a:"SoC", full:"System on a Chip", note:"Full system integrated onto one chip (embedded devices).", ch:11},

 // ----- Chapter 12: Network Security -----
 {a:"ACL", full:"Access Control List", note:"Rules on devices defining allowed/blocked traffic.", ch:12},
 {a:"NAC", full:"Network Access Control", note:"Authenticates/checks devices before granting network access.", ch:12},
 {a:"VLAN", full:"Virtual Local Area Network", note:"Logical network segmentation on a switch.", ch:12},
 {a:"VPN", full:"Virtual Private Network", note:"Encrypted tunnel over an untrusted network.", ch:12},
 {a:"IPsec", full:"Internet Protocol Security", note:"Secures IP traffic (AH + ESP); used for VPNs.", ch:12},
 {a:"ESP", full:"Encapsulating Security Payload", note:"IPsec component providing encryption.", ch:12},
 {a:"AH", full:"Authentication Header", note:"IPsec component providing integrity/authentication.", ch:12},
 {a:"IKE", full:"Internet Key Exchange", note:"Negotiates IPsec security associations/keys.", ch:12},
 {a:"NGFW", full:"Next-Generation Firewall", note:"Firewall with app awareness, IPS, deep inspection.", ch:12},
 {a:"WAF", full:"Web Application Firewall", note:"Filters HTTP to block SQLi/XSS against web apps.", ch:12},
 {a:"UTM", full:"Unified Threat Management", note:"One appliance combining many security functions.", ch:12},
 {a:"IDS", full:"Intrusion Detection System", note:"Detects and alerts on malicious traffic (passive).", ch:12},
 {a:"IPS", full:"Intrusion Prevention System", note:"Inline system that detects AND blocks attacks.", ch:12},
 {a:"NIDS", full:"Network-based Intrusion Detection System", note:"Monitors network traffic for threats.", ch:12},
 {a:"NIPS", full:"Network-based Intrusion Prevention System", note:"Blocks malicious network traffic inline.", ch:12},
 {a:"DDoS", full:"Distributed Denial of Service", note:"Flood from many compromised hosts (a botnet).", ch:12},
 {a:"DoS", full:"Denial of Service", note:"Overwhelms a target to make it unavailable.", ch:12},
 {a:"DNS", full:"Domain Name System", note:"Resolves names to IPs; target of poisoning attacks.", ch:12},
 {a:"DNSSEC", full:"DNS Security Extensions", note:"Signs DNS records to prevent spoofing/poisoning.", ch:12},
 {a:"DHCP", full:"Dynamic Host Configuration Protocol", note:"Auto-assigns IP addresses; can be spoofed (rogue DHCP).", ch:12},
 {a:"ARP", full:"Address Resolution Protocol", note:"Maps IP↔MAC; abused via ARP poisoning.", ch:12},
 {a:"NAT", full:"Network Address Translation", note:"Translates private↔public IPs.", ch:12},
 {a:"PAT", full:"Port Address Translation", note:"Many private IPs share one public IP via ports.", ch:12},
 {a:"SPF", full:"Sender Policy Framework", note:"Email: authorizes which servers may send for a domain.", ch:12},
 {a:"DKIM", full:"DomainKeys Identified Mail", note:"Email: signs messages to verify origin/integrity.", ch:12},
 {a:"DMARC", full:"Domain-based Message Authentication, Reporting & Conformance", note:"Email: policy tying SPF+DKIM together.", ch:12},
 {a:"FIM", full:"File Integrity Monitoring", note:"Alerts when important files change vs. a baseline.", ch:12},
 {a:"SASE", full:"Secure Access Service Edge", note:"Cloud-delivered networking + security (SD-WAN + ZTNA, etc.).", ch:12},
 {a:"SD-WAN", full:"Software-Defined Wide Area Network", note:"Software-managed WAN across any transport.", ch:12},
 {a:"SWG", full:"Secure Web Gateway", note:"Filters/inspects outbound web traffic.", ch:12},
 {a:"SSH", full:"Secure Shell", note:"Encrypted remote admin (replaces Telnet); port 22.", ch:12},
 {a:"SFTP", full:"SSH File Transfer Protocol", note:"Secure file transfer over SSH.", ch:12},
 {a:"FTPS", full:"File Transfer Protocol Secure", note:"FTP secured with TLS.", ch:12},
 {a:"HTTP", full:"Hypertext Transfer Protocol", note:"Web protocol; cleartext (port 80).", ch:12},
 {a:"HTTPS", full:"Hypertext Transfer Protocol Secure", note:"HTTP over TLS (port 443).", ch:12},
 {a:"SMTP", full:"Simple Mail Transfer Protocol", note:"Sends email (port 25).", ch:12},
 {a:"IMAP", full:"Internet Message Access Protocol", note:"Retrieves email keeping it on the server.", ch:12},
 {a:"POP", full:"Post Office Protocol", note:"Retrieves email, typically downloading it.", ch:12},
 {a:"SNMP", full:"Simple Network Management Protocol", note:"Monitors/manages devices; use v3 for security.", ch:12},
 {a:"NTP", full:"Network Time Protocol", note:"Syncs clocks; abused in amplification DDoS.", ch:12},
 {a:"RDP", full:"Remote Desktop Protocol", note:"Windows remote GUI access (port 3389).", ch:12},
 {a:"SRTP", full:"Secure Real-time Transport Protocol", note:"Encrypts voice/video (VoIP) media.", ch:12},
 {a:"VoIP", full:"Voice over IP", note:"Voice calls over data networks.", ch:12},
 {a:"GRE", full:"Generic Routing Encapsulation", note:"Tunneling protocol (often paired with IPsec).", ch:12},
 {a:"L2TP", full:"Layer 2 Tunneling Protocol", note:"VPN tunneling protocol (paired with IPsec).", ch:12},

 // ----- Chapter 13: Wireless & Mobile Security -----
 {a:"AP", full:"Access Point", note:"Device providing Wi-Fi connectivity.", ch:13},
 {a:"WAP", full:"Wireless Access Point", note:"Same as AP; rogue/evil-twin APs are a threat.", ch:13},
 {a:"WPA", full:"Wi-Fi Protected Access", note:"Wi-Fi security; WPA2/WPA3 are current.", ch:13},
 {a:"WPA2", full:"Wi-Fi Protected Access 2", note:"Uses AES-CCMP; PSK or Enterprise (802.1X) modes.", ch:13},
 {a:"WPA3", full:"Wi-Fi Protected Access 3", note:"Current standard; uses SAE for stronger key exchange.", ch:13},
 {a:"WEP", full:"Wired Equivalent Privacy", note:"Obsolete, easily cracked Wi-Fi encryption.", ch:13},
 {a:"PSK", full:"Pre-Shared Key", note:"Shared Wi-Fi password (WPA Personal mode).", ch:13},
 {a:"SAE", full:"Simultaneous Authentication of Equals", note:"WPA3 handshake resisting offline cracking; adds PFS.", ch:13},
 {a:"EAP", full:"Extensible Authentication Protocol", note:"Auth framework for 802.1X (many variants).", ch:13},
 {a:"PEAP", full:"Protected EAP", note:"EAP wrapped in a TLS tunnel.", ch:13},
 {a:"TKIP", full:"Temporal Key Integrity Protocol", note:"Legacy WPA encryption; deprecated.", ch:13},
 {a:"CCMP", full:"Counter Mode CBC-MAC Protocol", note:"AES-based encryption used by WPA2.", ch:13},
 {a:"BYOD", full:"Bring Your Own Device", note:"Employees use personal devices for work.", ch:13},
 {a:"COPE", full:"Corporate-Owned, Personally Enabled", note:"Company device with some personal use allowed.", ch:13},
 {a:"CYOD", full:"Choose Your Own Device", note:"Pick from an approved company device list.", ch:13},
 {a:"MDM", full:"Mobile Device Management", note:"Centrally configure/secure/wipe mobile devices.", ch:13},
 {a:"UEM", full:"Unified Endpoint Management", note:"Manages mobile AND traditional endpoints together.", ch:13},
 {a:"NFC", full:"Near Field Communication", note:"Very short-range wireless (tap-to-pay).", ch:13},
 {a:"GPS", full:"Global Positioning System", note:"Location services; used for geofencing.", ch:13},
 {a:"SIM", full:"Subscriber Identity Module", note:"Cellular identity chip; target of SIM-swap fraud.", ch:13},
 {a:"WIDS", full:"Wireless Intrusion Detection System", note:"Detects rogue APs and wireless attacks.", ch:13},
 {a:"WIPS", full:"Wireless Intrusion Prevention System", note:"Detects AND blocks wireless threats.", ch:13},

 // ----- Chapter 14: Monitoring & Incident Response -----
 {a:"SIEM", full:"Security Information and Event Management", note:"Aggregates/correlates logs for detection & analysis.", ch:14},
 {a:"SOAR", full:"Security Orchestration, Automation, and Response", note:"Automates IR workflows via playbooks.", ch:14},
 {a:"SOC", full:"Security Operations Center", note:"Team/facility monitoring and responding to threats.", ch:14},
 {a:"IR", full:"Incident Response", note:"Process for handling security incidents.", ch:14},
 {a:"IRP", full:"Incident Response Plan", note:"Documented plan/roles for responding to incidents.", ch:14},
 {a:"CIRT", full:"Computer Incident Response Team", note:"Team that handles security incidents (a.k.a. CSIRT/CERT).", ch:14},
 {a:"CERT", full:"Computer Emergency Response Team", note:"Group coordinating incident response.", ch:14},
 {a:"PCAP", full:"Packet Capture", note:"Captured network traffic for analysis (Wireshark/tcpdump).", ch:14},
 {a:"NetFlow", full:"Network Flow", note:"Summary flow data: who talked, ports, volume, timing.", ch:14},

 // ----- Chapter 15: Digital Forensics -----
 {a:"FTK", full:"Forensic Toolkit", note:"Popular digital forensics analysis software.", ch:15},
 {a:"DD", full:"Data Dump (dd)", note:"Tool to create bit-by-bit forensic disk images.", ch:15},
 {a:"e-discovery", full:"Electronic Discovery", note:"Producing electronic evidence for legal cases.", ch:15},

 // ----- Chapter 16: Security Governance & Compliance -----
 {a:"AUP", full:"Acceptable Use Policy", note:"Defines permitted use of org systems/data.", ch:16},
 {a:"SLA", full:"Service-Level Agreement", note:"Contract guaranteeing performance/uptime.", ch:16},
 {a:"MOU", full:"Memorandum of Understanding", note:"Informal statement of intent between parties.", ch:16},
 {a:"MOA", full:"Memorandum of Agreement", note:"More formal agreement on roles/responsibilities.", ch:16},
 {a:"MSA", full:"Master Service Agreement", note:"Overarching contract terms for ongoing work.", ch:16},
 {a:"SOW", full:"Statement of Work", note:"Defines specific deliverables/tasks under an MSA.", ch:16},
 {a:"BPA", full:"Business Partners Agreement", note:"Agreement governing a business partnership.", ch:16},
 {a:"PCI DSS", full:"Payment Card Industry Data Security Standard", note:"Standard for protecting cardholder data.", ch:16},
 {a:"GDPR", full:"General Data Protection Regulation", note:"EU law protecting personal data/privacy.", ch:16},
 {a:"NIST", full:"National Institute of Standards and Technology", note:"Publishes CSF and the Risk Management Framework.", ch:16},
 {a:"CSF", full:"Cybersecurity Framework", note:"NIST framework: Identify, Protect, Detect, Respond, Recover (+Govern).", ch:16},
 {a:"RMF", full:"Risk Management Framework", note:"NIST process for managing security/privacy risk.", ch:16},
 {a:"ISO", full:"International Organization for Standardization", note:"Publishes ISO 27001 (ISMS) and related standards.", ch:16},
 {a:"DPO", full:"Data Protection Officer", note:"Oversees data protection compliance (GDPR role).", ch:16},
 {a:"MSSP", full:"Managed Security Service Provider", note:"Outsourced provider of security monitoring/operations.", ch:16},
 {a:"CISO", full:"Chief Information Security Officer", note:"Executive responsible for the security program.", ch:16},

 // ----- Chapter 17: Risk Management & Privacy -----
 {a:"SLE", full:"Single Loss Expectancy", note:"Expected loss from one event = Asset Value × Exposure Factor.", ch:17},
 {a:"ALE", full:"Annualized Loss Expectancy", note:"Yearly expected loss = SLE × ARO.", ch:17},
 {a:"ARO", full:"Annualized Rate of Occurrence", note:"How many times per year a risk is expected to occur.", ch:17},
 {a:"EF", full:"Exposure Factor", note:"% of an asset's value lost in a single incident.", ch:17},
 {a:"BIA", full:"Business Impact Analysis", note:"Identifies critical functions and impact of disruptions.", ch:17},
 {a:"DRP", full:"Disaster Recovery Plan", note:"Plan to recover systems/data after a disaster.", ch:17},
 {a:"PII", full:"Personally Identifiable Information", note:"Data that can identify an individual.", ch:17},
 {a:"PHI", full:"Protected Health Information", note:"Identifiable health data (protected by HIPAA).", ch:17},
 {a:"KRI", full:"Key Risk Indicator", note:"Metric giving early warning of rising risk.", ch:17}
];
