#!/usr/bin/env python3
"""Compile decks/ch*.json into flashcards-data.js so the SecCards app works
offline (no server / no fetch). Re-run after editing any deck JSON file."""
import glob, json, os, re

HERE = os.path.dirname(os.path.abspath(__file__))
DECKDIR = os.path.join(HERE, "decks")

# Per-chapter flavor: emoji + theme color + subtitle (CompTIA Security+ SY0-701,
# Chapple 9th ed. chapter titles).
FLAVOR = {
    1:  ("🛡️", "#6366f1", "Today's Security Professional"),
    2:  ("🌐", "#8b5cf6", "Cybersecurity Threat Landscape"),
    3:  ("🦠", "#ec4899", "Malicious Code"),
    4:  ("🎣", "#f59e0b", "Social Engineering & Password Attacks"),
    5:  ("🔍", "#10b981", "Security Assessment & Testing"),
    6:  ("💻", "#06b6d4", "Application Security"),
    7:  ("🔐", "#3b82f6", "Cryptography & the PKI"),
    8:  ("🪪", "#ef4444", "Identity & Access Management"),
    9:  ("🏛️", "#14b8a6", "Resilience & Physical Security"),
    10: ("☁️", "#a855f7", "Cloud & Virtualization Security"),
    11: ("🖥️", "#f97316", "Endpoint Security"),
    12: ("🌉", "#0ea5e9", "Network Security"),
    13: ("📶", "#84cc16", "Wireless & Mobile Security"),
    14: ("🚨", "#eab308", "Monitoring & Incident Response"),
    15: ("🔬", "#d946ef", "Digital Forensics"),
    16: ("📋", "#22c55e", "Security Governance & Compliance"),
    17: ("⚖️", "#38bdf8", "Risk Management & Privacy"),
}

decks = []
for path in glob.glob(os.path.join(DECKDIR, "ch*.json")):
    name = os.path.basename(path)
    m = re.match(r"ch(\d+)\.json", name)
    if not m:
        continue
    num = int(m.group(1))
    with open(path, encoding="utf-8") as f:
        cards = json.load(f)
    if not cards:
        continue
    emoji, color, title = FLAVOR.get(num, ("🃏", "#6366f1", name))
    decks.append({
        "id": "ch%d" % num,
        "num": num,
        "title": "Chapter %d" % num,
        "subtitle": title,
        "emoji": emoji,
        "color": color,
        "cards": cards,
    })

decks.sort(key=lambda d: d["num"])
out = "// Auto-generated by build_data.py — do not edit by hand.\n"
out += "window.FLASHCARD_DECKS = " + json.dumps(decks, ensure_ascii=False, indent=1) + ";\n"
with open(os.path.join(HERE, "flashcards-data.js"), "w", encoding="utf-8") as f:
    f.write(out)

print("Wrote flashcards-data.js: %d decks, %d cards total"
      % (len(decks), sum(len(d["cards"]) for d in decks)))
