// Auto-generated by build_data.py — do not edit by hand.
window.FLASHCARD_DECKS = [
 {
  "id": "ch1",
  "num": 1,
  "title": "Chapter 1",
  "subtitle": "Today's Security Professional",
  "emoji": "🛡️",
  "color": "#6366f1",
  "cards": [
   {
    "q": "What are the three core objectives of cybersecurity (the CIA triad)?",
    "a": "Confidentiality (no unauthorized access to data), Integrity (no unauthorized modification of data/systems), and Availability (info & systems ready for legitimate users when needed)."
   },
   {
    "q": "What is the DAD triad?",
    "a": "The opposite of CIA — the three key threats: Disclosure (breach of confidentiality), Alteration (breach of integrity), and Denial (breach of availability)."
   },
   {
    "q": "What is nonrepudiation?",
    "a": "Assurance that someone who took an action (e.g., sent a message) cannot later deny it. Commonly provided by digital signatures."
   },
   {
    "q": "What does the AAA framework stand for?",
    "a": "Authentication (prove identity), Authorization (what you're allowed to do), and Accounting (logging/tracking what you did)."
   },
   {
    "q": "What are the FOUR security control categories (by mechanism of action)?",
    "a": "Managerial (policies/procedures/risk mgmt), Operational (processes run by people, e.g., training, guards), Physical (locks, fences, cameras), and Technical (logical/system controls like firewalls, encryption)."
   },
   {
    "q": "What are the SIX security control types (by intent)?",
    "a": "Preventive, Deterrent, Detective, Corrective, Compensating, and Directive."
   },
   {
    "q": "Difference between a preventive and a deterrent control?",
    "a": "Preventive stops an incident from happening (e.g., firewall, locked door). Deterrent discourages an attacker from trying (e.g., warning sign, guard dog, visible cameras)."
   },
   {
    "q": "What is a detective control? Give an example.",
    "a": "A control that identifies and records an incident after/while it happens — e.g., logs, IDS, security cameras footage review, motion detectors."
   },
   {
    "q": "What is a corrective control?",
    "a": "A control that remediates damage or restores systems after an incident — e.g., backups/restoration, patching, a fire suppression system."
   },
   {
    "q": "What is a compensating control?",
    "a": "An alternative control used when the primary/expected control isn't feasible — it fills the gap and provides comparable protection (e.g., extra monitoring when you can't patch a legacy system)."
   },
   {
    "q": "What is a directive control?",
    "a": "A control that directs/guides behavior toward security compliance — e.g., policies, acceptable use agreements, signage telling employees what to do."
   },
   {
    "q": "What is a gap analysis?",
    "a": "A review that compares the current state of security controls against the desired/required state to identify and prioritize what's missing."
   },
   {
    "q": "What are the three states in which data must be protected?",
    "a": "Data at rest (stored), Data in transit/in motion (crossing a network), and Data in use (being processed in memory)."
   },
   {
    "q": "What is Data Loss Prevention (DLP)?",
    "a": "Technology that enforces information-handling policies to block exfiltration/theft. Host-based agents scan systems; network-based DLP watches transmissions. Detects sensitive data via pattern matching and/or digital watermarking."
   },
   {
    "q": "What is data minimization?",
    "a": "Reducing risk by collecting and retaining only the minimum sensitive data necessary — the best protection for data is to not have it at all."
   },
   {
    "q": "What three techniques achieve deidentification / data obfuscation?",
    "a": "Hashing (one-way fingerprint), Tokenization (replace data with a meaningless token mapped elsewhere), and Masking (hide part of the value, e.g., showing only last 4 digits)."
   },
   {
    "q": "Difference between hashing, tokenization, and masking?",
    "a": "Hashing = irreversible one-way value. Tokenization = reversible swap to a random token via a lookup vault. Masking = permanently redacts/hides portions of the data shown."
   },
   {
    "q": "What is data sovereignty?",
    "a": "The principle that data is subject to the laws and regulations of the country/jurisdiction where it is physically stored or collected."
   },
   {
    "q": "Name common data classifications.",
    "a": "Examples: Public, Private, Sensitive, Confidential, Critical, Proprietary, and Restricted. (Exact labels vary by organization; the point is tiering data by sensitivity.)"
   },
   {
    "q": "What data types are commonly regulated or specially protected?",
    "a": "PII (personally identifiable info), PHI (protected health info — HIPAA), financial/cardholder data (PCI DSS), intellectual property/trade secrets, and other 'regulated' data."
   },
   {
    "q": "What is segmentation/isolation as a data-protection strategy?",
    "a": "Separating systems and data into zones so that a compromise in one area can't easily reach others — limiting access and containing breaches."
   },
   {
    "q": "What are the main impact categories of a data breach?",
    "a": "Financial, Reputational, Identity theft, Strategic, Operational, and Compliance/legal risk. Risks often cross several categories at once."
   },
   {
    "q": "What is operational risk from a breach?",
    "a": "Risk to the organization's ability to carry out day-to-day functions — e.g., losing access to its own systems/data (an availability impact)."
   },
   {
    "q": "What is strategic risk?",
    "a": "Risk that a breach undermines the organization's ability to meet its major goals/long-term objectives."
   },
   {
    "q": "Why use encryption for data at rest and in transit?",
    "a": "It protects confidentiality: in transit it stops eavesdropping/sniffing; at rest it protects stored data if a device or data store is stolen or breached."
   }
  ]
 },
 {
  "id": "ch2",
  "num": 2,
  "title": "Chapter 2",
  "subtitle": "Cybersecurity Threat Landscape",
  "emoji": "🌐",
  "color": "#8b5cf6",
  "cards": [
   {
    "q": "What four attributes are used to classify threat actors?",
    "a": "Internal vs. external; level of sophistication/capability; resources/funding available; and motivation/intent."
   },
   {
    "q": "What is an unskilled attacker (script kiddie)?",
    "a": "A low-skill attacker who uses tools, scripts, and exploit code written by others without understanding how they work. Low sophistication, low resources."
   },
   {
    "q": "What is a hacktivist?",
    "a": "An attacker motivated by a political, social, or ideological cause rather than money. Skill and resources vary widely."
   },
   {
    "q": "Who are nation-state attackers and what is an APT?",
    "a": "Government-sponsored attackers with high resources and sophistication. They often operate as an Advanced Persistent Threat (APT) — well-funded, stealthy, and able to maintain long-term access. Common motivation: espionage."
   },
   {
    "q": "What is an insider threat?",
    "a": "A threat from someone with legitimate access (employee, contractor, partner) who misuses it — intentionally or accidentally — to harm the organization."
   },
   {
    "q": "What is shadow IT?",
    "a": "Hardware, software, or cloud services used within an organization without IT approval or knowledge — creating unmanaged risk and expanding the attack surface."
   },
   {
    "q": "What motivates organized crime attackers?",
    "a": "Almost always financial gain — extortion, ransomware, fraud, and selling stolen data. Typically well-resourced and sophisticated."
   },
   {
    "q": "What is a zero-day vulnerability/attack?",
    "a": "A flaw unknown to the vendor with no patch available, exploited before defenders are aware of it — leaving 'zero days' to prepare."
   },
   {
    "q": "Name common attacker motivations.",
    "a": "Data exfiltration, espionage, service disruption, blackmail, financial gain, philosophical/political belief, revenge, disruption/chaos, war, and (some believe) ethical reasons."
   },
   {
    "q": "What is a threat vector vs. an attack surface?",
    "a": "A threat vector is the method/path an attacker uses to gain access (e.g., phishing email). The attack surface is the total set of points where an attacker could try to enter or extract data."
   },
   {
    "q": "Name common threat vectors.",
    "a": "Message-based (email, SMS, IM), wired networks, wireless networks, systems/services, files & images, removable devices (USB), cloud services, and the supply chain."
   },
   {
    "q": "How can a removable device (USB) be a threat vector?",
    "a": "Attackers trick users into plugging in malicious drives (or drop them in parking lots) to deliver malware or steal data — bypassing network defenses physically."
   },
   {
    "q": "What is supply chain risk?",
    "a": "Risk that an attacker compromises an organization through its hardware, software, or service vendors — e.g., tampered hardware, malicious code in a dependency, or a breached managed service provider."
   },
   {
    "q": "What is OSINT (open source intelligence)?",
    "a": "Threat intelligence gathered from publicly available sources — websites, social media, public records, news, vendor advisories, and security blogs."
   },
   {
    "q": "Difference between open-source and proprietary/closed-source threat intelligence?",
    "a": "OSINT is free and public. Proprietary/closed-source intel is purchased from vendors who do their own research and sell curated feeds — often more timely and tailored."
   },
   {
    "q": "What is the dark web in a threat-intel context?",
    "a": "Hidden parts of the Internet (accessed via tools like Tor) where stolen data, exploits, and criminal services are bought and sold — a source of intelligence about threats."
   },
   {
    "q": "What is an Indicator of Compromise (IoC)?",
    "a": "Forensic evidence that a system may have been breached — e.g., malicious IP addresses, file hashes, domains, unusual traffic, or registry changes."
   },
   {
    "q": "What three factors are used to assess the quality/confidence of threat intelligence?",
    "a": "Timeliness (is it current?), Accuracy (is it correct?), and Relevance (does it apply to your environment?)."
   },
   {
    "q": "What are STIX and TAXII?",
    "a": "Standards for sharing threat intel. STIX (Structured Threat Information eXpression) is the standardized data format; TAXII (Trusted Automated eXchange of Indicator Information) is the protocol/transport used to share STIX data."
   },
   {
    "q": "What is an ISAC?",
    "a": "An Information Sharing and Analysis Center — an industry-specific group (e.g., financial, healthcare) that shares threat intelligence among its members."
   },
   {
    "q": "What are the 'hats' hackers wear?",
    "a": "White hat = authorized/ethical hacker. Black hat = malicious/unauthorized attacker. Gray hat = acts without authorization but without malicious intent (a mix of both)."
   },
   {
    "q": "What is a predictive analytics use of threat intelligence?",
    "a": "Analyzing collected threat data to anticipate likely future attacks/targets so defenders can prepare proactively rather than just react."
   }
  ]
 },
 {
  "id": "ch3",
  "num": 3,
  "title": "Chapter 3",
  "subtitle": "Malicious Code",
  "emoji": "🦠",
  "color": "#ec4899",
  "cards": [
   {
    "q": "What is ransomware?",
    "a": "Malware that encrypts (or threatens to publish) a victim's data and demands payment for the decryption key. Modern variants add 'double extortion' — stealing data and threatening to leak it."
   },
   {
    "q": "What is a Trojan?",
    "a": "Malware disguised as legitimate/desirable software. It performs malicious actions when run while appearing benign. Does not self-replicate."
   },
   {
    "q": "What is a RAT?",
    "a": "Remote Access Trojan — a Trojan that gives an attacker remote control of the infected system (often part of a botnet)."
   },
   {
    "q": "What is a worm and how does it differ from a virus?",
    "a": "A worm self-replicates and spreads across networks on its own, with no user action and no host file needed. A virus needs a host file and a user to execute it to spread."
   },
   {
    "q": "What is a botnet and C2?",
    "a": "A botnet is a network of compromised machines (bots/zombies) controlled by an attacker. C2 (command and control) is the infrastructure the attacker uses to issue commands to the bots."
   },
   {
    "q": "What is spyware?",
    "a": "Malware that secretly gathers information about a user (browsing, keystrokes, credentials) and sends it to an attacker."
   },
   {
    "q": "What is bloatware?",
    "a": "Unwanted pre-installed software that consumes resources and may introduce vulnerabilities. Not inherently malicious, but it increases attack surface and should be removed."
   },
   {
    "q": "What is a keylogger?",
    "a": "Software or hardware that records keystrokes to capture passwords, messages, and other sensitive input."
   },
   {
    "q": "What is a logic bomb?",
    "a": "Malicious code that lies dormant until a specific condition or time triggers it (e.g., a date, or a fired employee's account being deleted)."
   },
   {
    "q": "What is a rootkit?",
    "a": "Malware that gains privileged (root/admin) access and hides its presence — often by modifying the OS kernel or boot process — making it very hard to detect and remove."
   },
   {
    "q": "What is fileless malware?",
    "a": "Malware that runs in memory and abuses legitimate system tools (e.g., PowerShell, WMI) instead of writing files to disk, evading traditional signature-based antivirus."
   },
   {
    "q": "What is a PUP?",
    "a": "A Potentially Unwanted Program — software bundled with downloads that the user didn't really want (adware, toolbars). Annoying and risky but not always overtly malicious."
   },
   {
    "q": "What is a backdoor?",
    "a": "A hidden method of bypassing normal authentication to gain access to a system — often installed by malware (or left by developers) for later re-entry."
   },
   {
    "q": "Name common indicators of compromise (IoCs) associated with malware.",
    "a": "C2 traffic patterns, known-bad IPs/domains/hostnames, unusual use of system utilities, lateral movement, unexpected file/dir creation, file encryption, and data exfiltration."
   },
   {
    "q": "How are malware signatures used, and what is their limitation?",
    "a": "Signatures are unique patterns identifying known malware files; antivirus matches them to detect threats. Limitation: malware authors use polymorphism/obfuscation to change signatures and evade detection."
   },
   {
    "q": "What is a polymorphic virus?",
    "a": "A virus that changes its own code/signature each time it replicates to evade signature-based detection, while keeping the same underlying function."
   },
   {
    "q": "What are the general steps to mitigate/remove malware?",
    "a": "Identify and isolate the infected system, remove the malicious files (manually or with tools), and — for serious infections like rootkits — reinstall the OS or restore from a known-good backup to ensure full removal."
   },
   {
    "q": "What was Stuxnet, and why is it notable?",
    "a": "A highly sophisticated nation-state worm that targeted industrial control systems (Iranian centrifuges). It's the classic example of malware causing physical/real-world damage."
   }
  ]
 },
 {
  "id": "ch4",
  "num": 4,
  "title": "Chapter 4",
  "subtitle": "Social Engineering & Password Attacks",
  "emoji": "🎣",
  "color": "#f59e0b",
  "cards": [
   {
    "q": "What is social engineering?",
    "a": "Manipulating people into revealing information or taking actions that compromise security — exploiting human psychology rather than technical flaws."
   },
   {
    "q": "Name the key psychological principles social engineers exploit.",
    "a": "Authority, Intimidation, Consensus/social proof, Scarcity, Urgency, Familiarity/liking, and Trust."
   },
   {
    "q": "What is phishing?",
    "a": "Fraudulent messages (usually email) impersonating a trusted source to trick victims into revealing credentials, clicking malicious links, or opening attachments."
   },
   {
    "q": "What is spear phishing vs. whaling?",
    "a": "Spear phishing targets a specific individual or group with tailored content. Whaling is spear phishing aimed at high-value targets like executives (the 'big fish')."
   },
   {
    "q": "What are vishing and smishing?",
    "a": "Vishing = phishing over voice/phone calls. Smishing = phishing over SMS text messages."
   },
   {
    "q": "What is Business Email Compromise (BEC)?",
    "a": "An attack where a scammer impersonates (or compromises) a trusted executive/vendor email account to trick employees into wiring money or sending sensitive data."
   },
   {
    "q": "What is pretexting?",
    "a": "Inventing a believable scenario/backstory to justify a request and gain trust — usually paired with impersonation to make the social-engineering attack convincing."
   },
   {
    "q": "What is a watering hole attack?",
    "a": "Compromising a website that the target group is known to visit, so victims get infected simply by visiting a trusted site."
   },
   {
    "q": "What is typosquatting?",
    "a": "Registering domains with common misspellings of popular sites (e.g., gooogle.com) to catch users who mistype a URL and serve them malicious content."
   },
   {
    "q": "What is brand impersonation?",
    "a": "Mimicking a trusted brand's logos, emails, and websites to make malicious communications look legitimate and trick users into trusting them."
   },
   {
    "q": "What is the difference between misinformation and disinformation?",
    "a": "Misinformation = false info spread without intent to deceive. Disinformation = false info spread deliberately to deceive or manipulate."
   },
   {
    "q": "What is pharming?",
    "a": "Redirecting users from a legitimate website to a fraudulent one — typically by poisoning DNS or modifying the hosts file — even when the correct URL is entered."
   },
   {
    "q": "Online vs. offline password attacks?",
    "a": "Online attacks target a live system's login (limited by lockouts/rate limits). Offline attacks crack a stolen password hash store on the attacker's own hardware with no such limits."
   },
   {
    "q": "What is a brute-force password attack?",
    "a": "Systematically trying every possible character combination until the correct password is found."
   },
   {
    "q": "What is a dictionary attack?",
    "a": "Trying passwords from a precompiled list of likely/common words and passwords instead of every possible combination."
   },
   {
    "q": "What is password spraying?",
    "a": "Trying a few common passwords against MANY accounts (instead of many passwords against one) to avoid triggering account lockouts."
   },
   {
    "q": "What is a rainbow table and how do you defend against it?",
    "a": "A precomputed table of password hashes used to reverse hashes quickly. Defense: salting (adding random data to each password before hashing) makes precomputed tables useless."
   },
   {
    "q": "Why are MD5 hashes and plaintext storage dangerous for passwords?",
    "a": "Plaintext and weak/fast hashes like MD5 are easy to crack or read outright. Strong, salted, slow hashing (e.g., bcrypt) should be used to protect stored passwords."
   }
  ]
 },
 {
  "id": "ch5",
  "num": 5,
  "title": "Chapter 5",
  "subtitle": "Security Assessment & Testing",
  "emoji": "🔍",
  "color": "#10b981",
  "cards": [
   {
    "q": "What is vulnerability management?",
    "a": "The ongoing process of identifying, evaluating, prioritizing, and remediating security weaknesses across systems, applications, and devices."
   },
   {
    "q": "What factors determine vulnerability scan frequency?",
    "a": "Regulatory/compliance requirements, the organization's risk appetite, technical constraints (impact on systems), and the workflow/business needs."
   },
   {
    "q": "Credentialed vs. non-credentialed scan?",
    "a": "A credentialed scan logs in with valid accounts to see configuration details from the inside (more accurate). A non-credentialed scan probes from outside without logging in (sees what an attacker without creds would)."
   },
   {
    "q": "Internal vs. external scan perspective?",
    "a": "Internal scans run from inside the network (what an insider/attacker who's already in would see). External scans run from outside (what an Internet attacker sees, e.g., the perimeter)."
   },
   {
    "q": "Agent-based vs. agentless scanning?",
    "a": "Agent-based installs software on each host to report continuously, even when offline/remote. Agentless (server-based) scans remotely over the network with no installed software."
   },
   {
    "q": "What is a false positive vs. a false negative in scanning?",
    "a": "False positive = scanner reports a vulnerability that doesn't actually exist. False negative = scanner misses a vulnerability that does exist (the more dangerous one)."
   },
   {
    "q": "What is CVE?",
    "a": "Common Vulnerabilities and Exposures — a standardized dictionary that assigns a unique ID to each publicly known vulnerability so everyone refers to it consistently."
   },
   {
    "q": "What is CVSS?",
    "a": "Common Vulnerability Scoring System — a 0–10 standard for rating the severity of a vulnerability based on its exploitability and impact."
   },
   {
    "q": "What are the CVSS base score severity ranges?",
    "a": "0.0 = None, 0.1–3.9 = Low, 4.0–6.9 = Medium, 7.0–8.9 = High, 9.0–10.0 = Critical."
   },
   {
    "q": "Name the CVSS base metrics.",
    "a": "Attack Vector, Attack Complexity, Privileges Required, User Interaction, Scope, and the impacts to Confidentiality, Integrity, and Availability."
   },
   {
    "q": "What does the CVSS Attack Vector metric describe?",
    "a": "How the vulnerability is exploited / how 'close' the attacker must be — Network (remote, highest risk), Adjacent, Local, or Physical (lowest risk)."
   },
   {
    "q": "What is SCAP?",
    "a": "Security Content Automation Protocol — a suite of standards (including CVE and CVSS) that lets security tools automatically share, measure, and standardize vulnerability data."
   },
   {
    "q": "What is penetration testing?",
    "a": "Authorized simulated attacks where testers actively attempt to exploit vulnerabilities to demonstrate real-world risk, going beyond a passive vulnerability scan."
   },
   {
    "q": "Known, unknown, and partially known environment pentests?",
    "a": "Known environment = testers have full info (white box). Unknown environment = no prior info (black box). Partially known = some info given (gray box)."
   },
   {
    "q": "What are 'rules of engagement' in a pentest?",
    "a": "The agreed boundaries of the test — scope, targets, timing, allowed techniques, and points of contact — defined before testing begins."
   },
   {
    "q": "List typical phases of a penetration test.",
    "a": "Reconnaissance → gaining initial access → privilege escalation → lateral movement/pivoting → establishing persistence → and finally cleanup (restore systems, remove traces)."
   },
   {
    "q": "What are war driving and war flying?",
    "a": "Reconnaissance techniques: driving (or flying a drone) around an area to discover and map wireless networks and access points."
   },
   {
    "q": "What is privilege escalation vs. lateral movement?",
    "a": "Privilege escalation = gaining higher-level rights on a system (e.g., user → admin). Lateral movement/pivoting = using a compromised system to reach and compromise other systems."
   },
   {
    "q": "What is persistence in an attack?",
    "a": "Establishing a foothold (backdoor, scheduled task, new account) so the attacker keeps access even after the original vulnerability is patched or the system reboots."
   },
   {
    "q": "What is a bug bounty program?",
    "a": "A program that pays external security researchers financial rewards for responsibly finding and reporting vulnerabilities, incentivizing 'hacking for good.'"
   },
   {
    "q": "What is responsible (coordinated) disclosure?",
    "a": "Privately reporting a vulnerability to the vendor and giving them time to fix it before any public disclosure."
   },
   {
    "q": "What is a security audit and what is an attestation?",
    "a": "An audit is a formal examination of security controls (by internal or third-party auditors). The attestation is the auditors' formal statement about whether controls are adequate and effective."
   },
   {
    "q": "What are the stages of the vulnerability life cycle?",
    "a": "Identification → Analysis (confirm/prioritize with CVE & CVSS) → Response & remediation → Validation of remediation → Reporting."
   },
   {
    "q": "What is threat hunting?",
    "a": "Proactively searching systems for indicators of compromise under the assumption that a breach has already occurred, rather than waiting for an alert."
   },
   {
    "q": "Possible responses to a confirmed vulnerability?",
    "a": "Apply a patch, isolate the affected system, implement a compensating control, transfer the risk (e.g., insurance), or formally accept the risk."
   }
  ]
 },
 {
  "id": "ch6",
  "num": 6,
  "title": "Chapter 6",
  "subtitle": "Application Security",
  "emoji": "💻",
  "color": "#06b6d4",
  "cards": [
   {
    "q": "What is the SDLC and its typical environments?",
    "a": "Software Development Life Cycle — the standardized process for building software. Code moves through Development → Test → Staging → Production environments."
   },
   {
    "q": "What is DevSecOps?",
    "a": "Integrating security into DevOps so security is built in throughout development and operations ('shift left'), rather than bolted on at the end."
   },
   {
    "q": "What is CI/CD?",
    "a": "Continuous Integration / Continuous Deployment — automatically and frequently merging, testing, and deploying code changes, with security testing built into the pipeline."
   },
   {
    "q": "What is input validation and why is it the key web defense?",
    "a": "Checking that user-supplied data conforms to expected format/length/type before processing it. It's the primary defense against injection and XSS attacks."
   },
   {
    "q": "What is OWASP?",
    "a": "Open Worldwide Application Security Project — a nonprofit that publishes web-app security guidance, including the well-known OWASP Top 10 list of common risks."
   },
   {
    "q": "Static (SAST) vs. dynamic (DAST) code analysis?",
    "a": "Static analysis reviews source code without running it. Dynamic analysis tests the application while it's running. Both find different classes of flaws."
   },
   {
    "q": "What is fuzzing?",
    "a": "A dynamic testing technique that feeds large amounts of random/malformed input to an application to find crashes and vulnerabilities."
   },
   {
    "q": "What is SQL injection (SQLi)?",
    "a": "Inserting malicious SQL into application input so the database executes unintended commands — allowing data theft, modification, or bypassing authentication."
   },
   {
    "q": "Blind content-based vs. blind timing-based SQL injection?",
    "a": "Both infer data when no direct output is shown. Content-based observes differences in the page response (true/false). Timing-based uses deliberate delays (e.g., sleep) to infer answers from how long responses take."
   },
   {
    "q": "What is command injection?",
    "a": "An attack where input is passed to the operating system shell, letting the attacker execute arbitrary OS commands on the server."
   },
   {
    "q": "What is Cross-Site Scripting (XSS)?",
    "a": "Injecting malicious scripts into a trusted website so they run in other users' browsers — stealing cookies/sessions or defacing content."
   },
   {
    "q": "Reflected vs. stored (persistent) vs. DOM-based XSS?",
    "a": "Reflected: script comes from the request and is echoed back immediately (e.g., via a link). Stored: script is saved on the server and served to all visitors. DOM-based: occurs entirely in the client-side script/DOM."
   },
   {
    "q": "What is Cross-Site Request Forgery (CSRF/XSRF)?",
    "a": "Tricking an authenticated user's browser into sending an unwanted request to a site they're logged into, performing actions without consent. Defended with anti-CSRF tokens."
   },
   {
    "q": "What is a buffer overflow?",
    "a": "Writing more data to a memory buffer than it can hold, overwriting adjacent memory — potentially crashing the program or letting an attacker run arbitrary code."
   },
   {
    "q": "What is a race condition (TOCTOU)?",
    "a": "A timing flaw exploited between the time a resource is checked and the time it's used (Time-Of-Check to Time-Of-Use), letting an attacker change the resource in between."
   },
   {
    "q": "What is an Insecure Direct Object Reference (IDOR)?",
    "a": "An authorization flaw where changing a reference in a request (e.g., ?id=123 to ?id=124) lets a user access another user's data because access isn't properly checked."
   },
   {
    "q": "What is directory (path) traversal?",
    "a": "Using sequences like ../ in input to access files outside the intended directory — e.g., reading /etc/passwd or other restricted files."
   },
   {
    "q": "What is LFI vs. RFI (file inclusion)?",
    "a": "Local File Inclusion includes a file already on the server; Remote File Inclusion pulls and executes a file from an attacker-controlled remote server. Both abuse insecure file-include functions."
   },
   {
    "q": "What is privilege escalation in an application context?",
    "a": "Exploiting a flaw to gain higher permissions than intended — vertical (user→admin) or horizontal (accessing another same-level user's resources)."
   },
   {
    "q": "What is an unvalidated redirect?",
    "a": "When an app redirects users to a URL taken from unchecked input, letting attackers send victims to malicious sites while appearing to use a trusted domain."
   },
   {
    "q": "What is code signing?",
    "a": "Digitally signing software with the developer's private key so users can verify it came from a trusted source and wasn't tampered with."
   },
   {
    "q": "What is sandboxing?",
    "a": "Running code in an isolated, restricted environment so that if it's malicious or buggy it can't affect the rest of the system."
   },
   {
    "q": "Key benefits and drawbacks of automation/scripting in security?",
    "a": "Benefits: efficiency, consistent baselines, scalability, faster reaction, workforce multiplier. Drawbacks: complexity, cost, a single point of failure, and accumulating technical debt."
   },
   {
    "q": "What is API security and a key API risk?",
    "a": "Protecting application programming interfaces with authentication, authorization, input validation, and rate limiting. A key risk is exposing APIs without proper access controls (e.g., allowing IDOR or data scraping)."
   }
  ]
 },
 {
  "id": "ch7",
  "num": 7,
  "title": "Chapter 7",
  "subtitle": "Cryptography & the PKI",
  "emoji": "🔐",
  "color": "#3b82f6",
  "cards": [
   {
    "q": "What are the four goals of cryptography?",
    "a": "Confidentiality (secrecy via encryption), Integrity (detect tampering), Authentication (verify identity), and Nonrepudiation (sender can't deny sending)."
   },
   {
    "q": "Symmetric vs. asymmetric encryption?",
    "a": "Symmetric uses one shared secret key for both encrypt and decrypt (fast). Asymmetric uses a key pair — public and private (slower, solves key distribution)."
   },
   {
    "q": "In asymmetric crypto, which key encrypts and which decrypts?",
    "a": "Anything encrypted with one key of the pair can only be decrypted with the other. For confidentiality: encrypt with the recipient's PUBLIC key; they decrypt with their PRIVATE key."
   },
   {
    "q": "Name common symmetric algorithms.",
    "a": "AES (current standard, 128/192/256-bit), 3DES (legacy), DES (broken/obsolete), Blowfish, Twofish, and RC4 (insecure stream cipher)."
   },
   {
    "q": "What is AES and why is it preferred?",
    "a": "Advanced Encryption Standard — a fast, strong symmetric block cipher with 128/192/256-bit keys. It's the modern standard for bulk encryption."
   },
   {
    "q": "Block cipher vs. stream cipher?",
    "a": "Block ciphers encrypt fixed-size blocks of data (e.g., AES, 128-bit blocks). Stream ciphers encrypt data one bit/byte at a time (e.g., RC4, ChaCha20)."
   },
   {
    "q": "Name common asymmetric algorithms.",
    "a": "RSA (factoring large primes), ECC (elliptic curve — strong with smaller keys, good for mobile/IoT), Diffie–Hellman (key exchange), and ElGamal."
   },
   {
    "q": "What is Diffie–Hellman?",
    "a": "A key-exchange algorithm that lets two parties securely agree on a shared secret over an insecure channel without ever transmitting the key itself."
   },
   {
    "q": "What is hashing and what are its properties?",
    "a": "A one-way function producing a fixed-length digest from input. It's irreversible and collision-resistant; the same input always yields the same hash. Used for integrity, not secrecy."
   },
   {
    "q": "Name common hashing algorithms (and which are weak).",
    "a": "SHA-2 (e.g., SHA-256) and SHA-3 are strong/current. MD5 and SHA-1 are considered broken (collision attacks) and should not be used for security."
   },
   {
    "q": "What is HMAC?",
    "a": "Hash-based Message Authentication Code — combines a hash with a secret key to provide both integrity AND authentication of a message."
   },
   {
    "q": "How is a digital signature created and verified?",
    "a": "Create: hash the message, then encrypt the hash with the SENDER's PRIVATE key. Verify: decrypt with the sender's PUBLIC key and compare to a freshly computed hash. Provides integrity, authentication, and nonrepudiation."
   },
   {
    "q": "What is salting, and what does it protect against?",
    "a": "Adding random data to a password before hashing so identical passwords get different hashes. It defeats rainbow tables and precomputed-hash attacks."
   },
   {
    "q": "What is key stretching? Name examples.",
    "a": "Making weak keys/passwords harder to crack by repeatedly hashing them (slowing brute force). Examples: PBKDF2, bcrypt, and Argon2."
   },
   {
    "q": "What is a PKI?",
    "a": "Public Key Infrastructure — the system of certificate authorities, certificates, and policies that lets parties securely exchange and trust public keys."
   },
   {
    "q": "What is a Certificate Authority (CA)?",
    "a": "A trusted entity that issues and digitally signs digital certificates, vouching that a public key belongs to its stated owner."
   },
   {
    "q": "What is a digital certificate (X.509)?",
    "a": "A signed electronic document binding a public key to an identity (person, server, org), issued by a CA in the X.509 standard format."
   },
   {
    "q": "What is a CSR?",
    "a": "Certificate Signing Request — a request (containing your public key and identity info) sent to a CA to obtain a signed digital certificate."
   },
   {
    "q": "What is the chain of trust / role of root vs. intermediate CAs?",
    "a": "Trust flows from a trusted Root CA (kept offline) down through Intermediate CAs that issue end-entity certificates. Validators follow the chain up to a trusted root."
   },
   {
    "q": "CRL vs. OCSP?",
    "a": "Both check if a certificate is revoked. A CRL (Certificate Revocation List) is a downloadable list of revoked certs. OCSP (Online Certificate Status Protocol) queries the CA in real time for one cert's status."
   },
   {
    "q": "What is OCSP stapling?",
    "a": "The web server obtains and 'staples' a recent signed OCSP response to its certificate during the TLS handshake, so the client doesn't have to contact the CA itself (faster, more private)."
   },
   {
    "q": "What is certificate pinning?",
    "a": "Hard-coding/associating a specific expected certificate or public key with a service, so the client rejects any other cert — preventing fraudulent-CA attacks."
   },
   {
    "q": "What is a wildcard certificate?",
    "a": "A certificate that secures a domain and all its subdomains (e.g., *.example.com) with a single cert."
   },
   {
    "q": "What is key escrow?",
    "a": "Storing a copy of cryptographic keys with a trusted third party so they can be recovered if lost — a tradeoff between recoverability and the risk of key exposure."
   },
   {
    "q": "What is perfect forward secrecy (PFS)?",
    "a": "Using ephemeral (one-time) session keys so that compromising a long-term private key later cannot decrypt past recorded sessions."
   },
   {
    "q": "TPM vs. HSM?",
    "a": "TPM (Trusted Platform Module) is a chip on a device's motherboard storing keys for that machine (e.g., for full-disk encryption). HSM (Hardware Security Module) is a dedicated, often network-attached device for high-volume enterprise key generation/storage."
   },
   {
    "q": "What is steganography?",
    "a": "Hiding data inside other files (images, audio, video) so the very existence of the message is concealed — secrecy through obscurity, not encryption."
   },
   {
    "q": "What is a blockchain?",
    "a": "An immutable, distributed public ledger secured by cryptography (hashing and digital signatures), where each block links to the previous one."
   },
   {
    "q": "Why is quantum computing a threat to cryptography?",
    "a": "Quantum computers could break current asymmetric algorithms (RSA, ECC) by quickly solving the math they rely on — driving the move to post-quantum (quantum-resistant) cryptography."
   },
   {
    "q": "What is the main weakness of symmetric encryption?",
    "a": "Key distribution — securely sharing the single secret key with all parties is difficult, and the number of keys grows rapidly as users are added."
   }
  ]
 },
 {
  "id": "ch8",
  "num": 8,
  "title": "Chapter 8",
  "subtitle": "Identity & Access Management",
  "emoji": "🪪",
  "color": "#ef4444",
  "cards": [
   {
    "q": "Distinguish identification, authentication, authorization, and accounting.",
    "a": "Identification = claiming an identity (username). Authentication = proving it (password). Authorization = what you're allowed to do. Accounting = logging what you did."
   },
   {
    "q": "What are the authentication factor categories?",
    "a": "Something you KNOW (password/PIN), something you HAVE (token/phone/smartcard), something you ARE (biometrics), somewhere you ARE (location), and something you DO (behavior)."
   },
   {
    "q": "What is multifactor authentication (MFA)?",
    "a": "Authentication requiring two or more DISTINCT factor types (e.g., password + phone token). Two passwords is NOT MFA — they're the same factor."
   },
   {
    "q": "What are FAR, FRR, and CER in biometrics?",
    "a": "FAR = False Acceptance Rate (wrong person let in — security risk). FRR = False Rejection Rate (right person denied — usability problem). CER = Crossover Error Rate, where FAR=FRR; lower CER = better system."
   },
   {
    "q": "HOTP vs. TOTP?",
    "a": "Both generate one-time passwords. HOTP is counter/event-based (changes when used). TOTP is time-based (changes every 30–60 seconds) — used by most authenticator apps."
   },
   {
    "q": "What is a FIDO2 / security key?",
    "a": "A hardware authenticator (e.g., YubiKey) supporting passwordless/phishing-resistant authentication using public-key cryptography instead of shared secrets."
   },
   {
    "q": "What is Single Sign-On (SSO)?",
    "a": "Letting a user authenticate once and access multiple applications/services without logging in again to each."
   },
   {
    "q": "What is federation?",
    "a": "Extending identity across organizations/domains so a user from one trusted org can access another org's resources using their home credentials."
   },
   {
    "q": "What is SAML and where is it used?",
    "a": "Security Assertion Markup Language — an XML-based standard for exchanging authentication/authorization data, widely used for browser-based enterprise SSO and federation."
   },
   {
    "q": "What are OAuth and OpenID Connect?",
    "a": "OAuth is an authorization framework (granting apps limited access to resources). OpenID Connect (OIDC) builds authentication on top of OAuth 2.0 (the 'log in with Google' pattern)."
   },
   {
    "q": "What is LDAP?",
    "a": "Lightweight Directory Access Protocol — used to query and manage directory services (like a central database of users, groups, and resources, e.g., Active Directory). LDAPS is the secure version."
   },
   {
    "q": "What is Kerberos?",
    "a": "A network authentication protocol that uses tickets and a trusted Key Distribution Center (KDC) to authenticate users without sending passwords over the network. Used by Active Directory."
   },
   {
    "q": "RADIUS vs. TACACS+?",
    "a": "Both are AAA protocols. RADIUS is an open standard (UDP), commonly for network access/Wi-Fi, and encrypts only the password. TACACS+ is Cisco (TCP), encrypts the entire payload, and separates AAA functions."
   },
   {
    "q": "Name common account types.",
    "a": "User accounts, Guest accounts, Administrative/privileged accounts, and Service accounts (used by applications/services, not people)."
   },
   {
    "q": "What is privileged access management (PAM)?",
    "a": "Controls focused on securing administrative/privileged accounts — using techniques like just-in-time access, credential vaulting, and session monitoring."
   },
   {
    "q": "What is just-in-time (JIT) permissions and an ephemeral account?",
    "a": "JIT grants elevated rights only for the moment they're needed, then removes them. An ephemeral account exists only for the duration of a task, reducing standing privilege."
   },
   {
    "q": "What is provisioning and deprovisioning?",
    "a": "Provisioning = creating accounts and granting appropriate access (often at hiring). Deprovisioning = promptly disabling/removing access when no longer needed (e.g., termination) to prevent orphaned accounts."
   },
   {
    "q": "What is RBAC (role-based access control)?",
    "a": "Access is granted based on the user's ROLE/job function (e.g., 'Accountant'), simplifying management by assigning permissions to roles rather than individuals."
   },
   {
    "q": "What is ABAC (attribute-based access control)?",
    "a": "Access decisions are made dynamically based on ATTRIBUTES (of user, resource, action, environment) — e.g., department, time of day, location. Very flexible/fine-grained."
   },
   {
    "q": "What is MAC (mandatory access control)?",
    "a": "The SYSTEM enforces access based on security labels/clearances set by an administrator; users cannot change permissions. Used in high-security/military environments."
   },
   {
    "q": "What is DAC (discretionary access control)?",
    "a": "The data OWNER decides who gets access to their files/resources at their discretion (e.g., standard file sharing). Flexible but less centrally controlled."
   },
   {
    "q": "What is rule-based access control?",
    "a": "Access is governed by a set of system-enforced rules/conditions (e.g., firewall ACLs, 'no access after 6pm') applied uniformly regardless of role."
   },
   {
    "q": "What is the principle of least privilege?",
    "a": "Giving users/processes only the minimum access needed to do their job — and no more — to limit damage from compromise or misuse."
   },
   {
    "q": "What is separation of duties?",
    "a": "Splitting critical tasks among multiple people so no single individual can complete a sensitive action alone — reducing fraud and error."
   },
   {
    "q": "What are common password policy settings?",
    "a": "Length (most important), complexity, reuse history, expiration/age (max and min age), and lockout thresholds. Modern guidance favors length and MFA over forced frequent expiration."
   },
   {
    "q": "What is a password manager?",
    "a": "A tool that securely generates and stores unique strong passwords in an encrypted vault, reducing password reuse — unlocked by one master password."
   }
  ]
 },
 {
  "id": "ch9",
  "num": 9,
  "title": "Chapter 9",
  "subtitle": "Resilience & Physical Security",
  "emoji": "🏛️",
  "color": "#14b8a6",
  "cards": [
   {
    "q": "What is high availability (HA) and how is redundancy used to achieve it?",
    "a": "HA keeps systems/services running with minimal downtime. Redundancy — duplicate components, systems, networks, and sites — eliminates single points of failure so a failure doesn't cause an outage."
   },
   {
    "q": "What is geographic dispersal?",
    "a": "Placing redundant systems/backups in physically separate locations so a single local disaster (fire, flood, outage) can't take down both."
   },
   {
    "q": "What does a load balancer do?",
    "a": "Distributes incoming traffic across multiple servers to improve performance and availability. Modes include active/active (all working) and active/passive (standby takes over on failure)."
   },
   {
    "q": "What is clustering?",
    "a": "Grouping multiple servers to act as one system so that if one node fails, others continue serving — providing redundancy and scalability."
   },
   {
    "q": "Describe RAID 0, 1, 5, 6, and 10.",
    "a": "RAID 0 = striping (speed, no redundancy). RAID 1 = mirroring. RAID 5 = striping + 1 parity (survives 1 disk loss). RAID 6 = 2 parity (survives 2). RAID 10 = mirrored + striped (speed + redundancy)."
   },
   {
    "q": "Full, incremental, and differential backups?",
    "a": "Full = everything. Incremental = only data changed since the LAST backup (fast backup, slow restore). Differential = all data changed since the last FULL backup (slower backup, faster restore)."
   },
   {
    "q": "What is the 3-2-1 backup rule?",
    "a": "Keep 3 copies of data, on 2 different media types, with 1 copy stored offsite."
   },
   {
    "q": "Why are offsite backups preferred?",
    "a": "So a disaster (fire, flood, ransomware) affecting the primary site doesn't also destroy the backups — geographic separation protects recoverability."
   },
   {
    "q": "What are snapshots, journaling, and replication?",
    "a": "Snapshot = point-in-time copy of a system/volume. Journaling = logging changes to allow recovery to a consistent state. Replication = continuously copying data to another location for availability."
   },
   {
    "q": "RTO vs. RPO?",
    "a": "RTO (Recovery Time Objective) = how quickly you must restore service after an outage. RPO (Recovery Point Objective) = how much data loss is acceptable, i.e., how far back you can recover (drives backup frequency)."
   },
   {
    "q": "MTBF vs. MTTR?",
    "a": "MTBF (Mean Time Between Failures) = average time a system runs before failing (reliability). MTTR (Mean Time To Repair) = average time to fix it and restore service."
   },
   {
    "q": "Hot, warm, and cold disaster recovery sites?",
    "a": "Hot = fully equipped and running, near-instant failover (most expensive). Warm = equipped but needs setup/data load (hours). Cold = empty space/power only, longest to bring online (cheapest)."
   },
   {
    "q": "What is a restoration order and why does it matter?",
    "a": "A predetermined sequence for bringing systems back online during recovery, based on dependencies and business importance (e.g., restore network/auth before applications)."
   },
   {
    "q": "What is capacity planning?",
    "a": "Ensuring you have enough people, technology, and infrastructure to handle normal load AND recover from outages — avoiding being overwhelmed during incidents or growth."
   },
   {
    "q": "What is a UPS vs. a generator?",
    "a": "A UPS (battery) provides immediate, short-term power to bridge outages and allow safe shutdown/failover. A generator provides long-term backup power for extended outages."
   },
   {
    "q": "Name common DR testing methods.",
    "a": "Tabletop exercises (discussion-based walkthrough), failover testing, simulations, and parallel processing (running recovery systems alongside production)."
   },
   {
    "q": "What is an access control vestibule (mantrap)?",
    "a": "A small space with two interlocking doors where only one opens at a time, preventing tailgating/piggybacking by allowing one person through at a time."
   },
   {
    "q": "Name common physical perimeter controls.",
    "a": "Fences, lighting, bollards (vehicle barriers), signage, security guards, locks, badges, and surveillance cameras (CCTV)."
   },
   {
    "q": "Compare infrared, microwave, ultrasonic, and pressure sensors.",
    "a": "Detection sensors with different methods: infrared senses heat/motion, microwave/ultrasonic emit waves and detect reflection changes (motion), pressure detects weight/force. Choose based on environment and cost."
   },
   {
    "q": "What is tailgating/piggybacking?",
    "a": "An unauthorized person following an authorized person through a secure door. Defended by access control vestibules and security awareness."
   },
   {
    "q": "What is a Faraday cage?",
    "a": "An enclosure that blocks electromagnetic signals — used to prevent wireless emanations/eavesdropping or to isolate devices from RF."
   },
   {
    "q": "What is an air gap?",
    "a": "Physically isolating a system/network from all other networks (no connection) to protect highly sensitive systems from remote attack."
   },
   {
    "q": "Why does platform/technology diversity build resilience (and its cost)?",
    "a": "Using different vendors/technologies/clouds means a single product flaw or provider outage won't take everything down — but it adds complexity and cost to manage."
   }
  ]
 },
 {
  "id": "ch10",
  "num": 10,
  "title": "Chapter 10",
  "subtitle": "Cloud & Virtualization Security",
  "emoji": "☁️",
  "color": "#a855f7",
  "cards": [
   {
    "q": "What are the three major cloud SERVICE models?",
    "a": "IaaS (Infrastructure as a Service — raw compute/storage/network), PaaS (Platform as a Service — a platform to run your own apps), and SaaS (Software as a Service — a fully managed application)."
   },
   {
    "q": "Give an example of IaaS, PaaS, and SaaS.",
    "a": "IaaS = AWS EC2 virtual machines. PaaS = a managed app/database platform (e.g., Azure App Service). SaaS = Microsoft 365 or Gmail."
   },
   {
    "q": "What are the four cloud DEPLOYMENT models?",
    "a": "Public (shared, open to any customer), Private (dedicated to one organization), Community (shared among a specific group with common needs), and Hybrid (a blend of these)."
   },
   {
    "q": "Explain the shared responsibility model.",
    "a": "Security duties are split between the cloud provider and customer. As you move SaaS→PaaS→IaaS, the customer takes on MORE responsibility. The customer is ALWAYS responsible for their data and access management."
   },
   {
    "q": "Who secures what in IaaS vs. PaaS vs. SaaS?",
    "a": "IaaS: provider secures up to the hypervisor; customer secures the OS and up. PaaS: provider also secures the OS; customer secures apps/data. SaaS: provider secures almost everything; customer manages access controls and their data."
   },
   {
    "q": "What is multitenancy?",
    "a": "Multiple customers (tenants) sharing the same physical cloud infrastructure while being logically isolated from each other."
   },
   {
    "q": "Type 1 vs. Type 2 hypervisor?",
    "a": "Type 1 (bare-metal) runs directly on hardware (e.g., ESXi, Hyper-V) — more efficient/secure, used in data centers. Type 2 (hosted) runs on top of a host OS (e.g., VirtualBox) — for desktops/testing."
   },
   {
    "q": "What is VM escape?",
    "a": "An attack where malicious code breaks out of a guest virtual machine to access the hypervisor or other VMs on the host — a critical virtualization risk."
   },
   {
    "q": "What is VM sprawl?",
    "a": "The uncontrolled proliferation of virtual machines that go unmanaged, unpatched, and untracked — expanding the attack surface."
   },
   {
    "q": "Containers vs. virtual machines?",
    "a": "VMs virtualize hardware and each runs a full guest OS (heavier, stronger isolation). Containers share the host OS kernel and package just the app and dependencies (lightweight, faster, weaker isolation)."
   },
   {
    "q": "What is serverless computing (FaaS)?",
    "a": "A model where the cloud provider runs code on demand (functions) and fully manages the infrastructure — you only deploy code and pay per execution (e.g., AWS Lambda)."
   },
   {
    "q": "What is a CASB?",
    "a": "Cloud Access Security Broker — a security policy enforcement point between users and cloud services that provides visibility, access control, DLP, and threat protection for cloud usage."
   },
   {
    "q": "What is a cloud security group?",
    "a": "A virtual firewall for cloud instances that controls inbound/outbound traffic by rules — restricting which ports, protocols, and sources can reach a resource."
   },
   {
    "q": "What are public vs. private subnets in cloud network design?",
    "a": "Public subnets have routes to the Internet (for web-facing resources); private subnets do not (for databases/backends) — segmentation that limits exposure."
   },
   {
    "q": "What is Infrastructure as Code (IaC)?",
    "a": "Defining and provisioning infrastructure through machine-readable configuration files/code (e.g., Terraform), enabling consistent, repeatable, version-controlled deployments."
   },
   {
    "q": "What is Software-Defined Networking (SDN)?",
    "a": "Separating the network control plane (decision-making) from the data plane (forwarding), allowing centralized, programmable, software-based network management."
   },
   {
    "q": "What is secrets management in the cloud?",
    "a": "Securely storing and controlling access to sensitive credentials (API keys, passwords, certificates) in a dedicated vault rather than hard-coding them."
   },
   {
    "q": "How is high availability achieved within a cloud region?",
    "a": "By deploying resources across multiple availability zones (isolated data centers) so an outage in one zone doesn't take the application down."
   },
   {
    "q": "What is a key benefit of resource policies in the cloud?",
    "a": "They define and enforce who/what can access which cloud resources and how, providing fine-grained, auditable access control across the environment."
   }
  ]
 },
 {
  "id": "ch11",
  "num": 11,
  "title": "Chapter 11",
  "subtitle": "Endpoint Security",
  "emoji": "🖥️",
  "color": "#f97316",
  "cards": [
   {
    "q": "What is OS hardening?",
    "a": "Reducing a system's attack surface by disabling unnecessary services/ports, removing default accounts, changing default passwords, applying secure configurations, and patching."
   },
   {
    "q": "What is a security baseline?",
    "a": "A standardized, approved secure configuration applied to systems so all devices start from a known, consistent, hardened state (often based on benchmarks like CIS)."
   },
   {
    "q": "Why is patch management critical?",
    "a": "Applying vendor updates promptly closes known vulnerabilities in the OS and applications before attackers can exploit them — one of the most important endpoint defenses."
   },
   {
    "q": "What are secure boot, trusted boot, and measured boot?",
    "a": "Boot-process protections: Secure Boot verifies bootloader/firmware signatures, Trusted Boot continues verification into the OS/drivers, and Measured Boot records measurements (often to a TPM) for later attestation."
   },
   {
    "q": "What is a hardware root of trust / TPM's role?",
    "a": "A trusted hardware component (TPM) that securely stores keys and verifies boot integrity, anchoring trust in hardware that software can't easily tamper with."
   },
   {
    "q": "What is the difference between antivirus and EDR?",
    "a": "Traditional antivirus uses signatures to detect known malware. EDR (Endpoint Detection and Response) continuously monitors behavior, detects advanced/unknown threats, and enables investigation and automated response."
   },
   {
    "q": "What is XDR?",
    "a": "Extended Detection and Response — extends EDR by correlating data across endpoints, network, email, cloud, and more for unified, broader threat detection and response."
   },
   {
    "q": "What is a HIDS/HIPS?",
    "a": "Host-based Intrusion Detection/Prevention System — software on an endpoint that detects (HIDS) or detects AND blocks (HIPS) malicious activity targeting that host."
   },
   {
    "q": "What is a host-based firewall?",
    "a": "Firewall software running on an individual device that controls inbound/outbound traffic for just that host, complementing network firewalls."
   },
   {
    "q": "What is application allow listing vs. deny/block listing?",
    "a": "Allow listing permits ONLY approved applications to run (default-deny — very secure). Deny/block listing blocks specific known-bad apps but allows everything else (less secure)."
   },
   {
    "q": "What is Full Disk Encryption (FDE)?",
    "a": "Encrypting the entire drive so all data is protected at rest — if the device is lost or stolen, the data is unreadable without the key (e.g., BitLocker, FileVault)."
   },
   {
    "q": "FDE vs. file/volume encryption?",
    "a": "FDE encrypts the whole drive automatically. File/volume encryption protects only selected files or partitions, leaving the rest of the drive unencrypted."
   },
   {
    "q": "What is a self-encrypting drive (SED)?",
    "a": "A drive with built-in hardware encryption that automatically encrypts all data written to it, with no performance hit on the CPU."
   },
   {
    "q": "Name common media sanitization methods.",
    "a": "Wiping/overwriting (secure erase), degaussing (magnetically erasing — for HDDs/tapes), cryptographic erase (destroying the encryption key), and physical destruction (shredding, incineration)."
   },
   {
    "q": "When should you physically destroy media vs. wipe it?",
    "a": "Destroy when data is highly sensitive or the media can't be reliably wiped (e.g., failed/SSD drives, or strict policy). Wiping is fine for reuse of functioning media with lower-sensitivity data."
   },
   {
    "q": "What is asset management and its scope?",
    "a": "Tracking and managing hardware, software, and data assets from acquisition through their life cycle to disposal/decommissioning — including inventory, ownership, and classification."
   },
   {
    "q": "What are SCADA and ICS systems?",
    "a": "Industrial Control Systems / Supervisory Control and Data Acquisition — systems that monitor and control physical industrial processes (factories, power plants, utilities). They often need special, isolated security."
   },
   {
    "q": "What unique security concerns do IoT devices pose?",
    "a": "Internet-connected devices often have weak/default credentials, infrequent patching, limited security features, and may be controlled by third parties — expanding the attack surface."
   },
   {
    "q": "What is an embedded system / RTOS?",
    "a": "An embedded system is a computer built into a larger device for a dedicated function. An RTOS (Real-Time Operating System) runs time-critical tasks; both are often hard to patch and need special protection."
   },
   {
    "q": "Why is end-of-life/legacy hardware a security risk?",
    "a": "Once a vendor stops releasing patches (end-of-life), known vulnerabilities remain unfixed forever — requiring isolation or compensating controls."
   },
   {
    "q": "What is configuration management?",
    "a": "Establishing and maintaining consistent, documented system settings/baselines and tracking changes so systems stay in a known, secure, supportable state."
   }
  ]
 },
 {
  "id": "ch12",
  "num": 12,
  "title": "Chapter 12",
  "subtitle": "Network Security",
  "emoji": "🌉",
  "color": "#0ea5e9",
  "cards": [
   {
    "q": "What is network segmentation and why use it?",
    "a": "Dividing a network into separate zones/subnets (often by risk or function) to contain breaches, limit lateral movement, and apply different security controls per zone."
   },
   {
    "q": "What is a screened subnet (DMZ)?",
    "a": "A separate network segment between the internet and internal network that hosts public-facing services (web, email), isolating them so a compromise doesn't directly expose the internal LAN."
   },
   {
    "q": "What is NAC (Network Access Control)?",
    "a": "Technology that authenticates and checks devices for compliance (patches, AV, config) before allowing them onto the network, blocking or quarantining untrusted/non-compliant devices."
   },
   {
    "q": "What is 802.1X?",
    "a": "A port-based network access control standard that requires devices to authenticate (often via RADIUS/EAP) before being granted network access on a switch port or Wi-Fi."
   },
   {
    "q": "What is a VLAN and how does it improve security?",
    "a": "A Virtual LAN logically segments a switch into separate broadcast domains, isolating groups of devices regardless of physical location to limit traffic and contain threats."
   },
   {
    "q": "Site-to-site vs. remote-access VPN?",
    "a": "Site-to-site connects entire networks (office-to-office) over the internet. Remote-access connects individual users/devices to the corporate network from anywhere."
   },
   {
    "q": "Full tunnel vs. split tunnel VPN?",
    "a": "Full tunnel routes ALL of the user's traffic through the VPN (more secure, more overhead). Split tunnel sends only corporate-bound traffic through the VPN and the rest directly to the internet (faster, less secure)."
   },
   {
    "q": "What is IPsec?",
    "a": "A protocol suite that secures IP traffic with authentication and encryption — commonly used for VPNs. Uses AH (integrity/auth) and ESP (encryption), in transport or tunnel mode."
   },
   {
    "q": "What is zero trust?",
    "a": "A security model that trusts nothing by default — every access request is continuously verified ('never trust, always verify') regardless of whether it's inside or outside the network perimeter."
   },
   {
    "q": "What is a jump server (jump box)?",
    "a": "A hardened, monitored host that administrators connect to first in order to reach systems in a more secure zone, providing a controlled single access point."
   },
   {
    "q": "Forward proxy vs. reverse proxy?",
    "a": "A forward proxy sits in front of clients (controls/filters their outbound access). A reverse proxy sits in front of servers (handles incoming requests, load balancing, and hides backend servers)."
   },
   {
    "q": "What is a web/content filter?",
    "a": "A control that allows or blocks access to websites/content based on URLs, categories, or rules — limiting what can enter or leave the network."
   },
   {
    "q": "IDS vs. IPS?",
    "a": "An IDS (Intrusion Detection System) detects and alerts on malicious activity (passive, out-of-band). An IPS (Intrusion Prevention System) sits inline and can actively block it."
   },
   {
    "q": "Signature-based vs. anomaly/behavior-based detection?",
    "a": "Signature-based matches known attack patterns (accurate for known threats, misses new ones). Anomaly/behavior-based flags deviations from a baseline (can catch unknown threats but more false positives)."
   },
   {
    "q": "What is a next-generation firewall (NGFW)?",
    "a": "A firewall that adds deep packet inspection, application awareness, integrated IPS, and identity/threat intelligence beyond basic port/protocol filtering."
   },
   {
    "q": "What is a WAF?",
    "a": "Web Application Firewall — filters and monitors HTTP traffic to protect web apps from attacks like SQL injection and XSS at the application layer."
   },
   {
    "q": "What is a stateful vs. stateless firewall?",
    "a": "A stateful firewall tracks the state of active connections and allows return traffic for established sessions. A stateless firewall filters each packet independently against rules with no connection memory."
   },
   {
    "q": "What is a UTM appliance?",
    "a": "Unified Threat Management — a single device combining many security functions (firewall, IPS, antivirus, web filtering, VPN, etc.)."
   },
   {
    "q": "What is out-of-band management?",
    "a": "Managing devices over a separate, dedicated channel/network (not the production data path) so admin access stays available and isolated from attackers on the main network."
   },
   {
    "q": "What do SPF, DKIM, and DMARC do?",
    "a": "Email anti-spoofing standards: SPF authorizes which servers can send for a domain, DKIM signs messages to verify integrity/origin, and DMARC ties them together with a policy on how to handle failures."
   },
   {
    "q": "What is DNSSEC?",
    "a": "DNS Security Extensions — adds digital signatures to DNS records so resolvers can verify responses are authentic and unaltered, defending against DNS spoofing/poisoning."
   },
   {
    "q": "Name secure replacements for insecure protocols.",
    "a": "FTP→SFTP/FTPS, Telnet→SSH, HTTP→HTTPS, LDAP→LDAPS, SNMPv1/2→SNMPv3, POP3/IMAP→POP3S/IMAPS, RTP→SRTP. They add encryption and/or authentication."
   },
   {
    "q": "What is an on-path (man-in-the-middle) attack?",
    "a": "An attacker secretly positions themselves between two parties to intercept, read, and possibly modify their communication."
   },
   {
    "q": "What is ARP poisoning?",
    "a": "Sending forged ARP messages to associate the attacker's MAC with another host's IP, redirecting traffic to the attacker — enabling on-path attacks on a LAN."
   },
   {
    "q": "DoS vs. DDoS?",
    "a": "A DoS (Denial of Service) attack overwhelms a target from one source. A DDoS uses many distributed, compromised systems (a botnet) to flood the target — harder to block."
   },
   {
    "q": "Reflected vs. amplified DDoS?",
    "a": "Reflected DDoS spoofs the victim's source address so responses flood the victim. Amplified DDoS sends small queries that generate large responses (e.g., DNS/NTP), multiplying the traffic aimed at the victim."
   },
   {
    "q": "What is a honeypot vs. a honeytoken?",
    "a": "A honeypot is a decoy system designed to lure and study attackers. A honeytoken is fake data/credentials planted so that any use of it reveals an intruder."
   },
   {
    "q": "What is File Integrity Monitoring (FIM)?",
    "a": "Software that detects unauthorized changes to important files by comparing them against known-good baselines/hashes and alerting on modifications."
   },
   {
    "q": "What is SASE?",
    "a": "Secure Access Service Edge — a cloud-delivered model that combines networking (SD-WAN) and security services (CASB, ZTNA, FWaaS) into one framework for distributed users."
   },
   {
    "q": "What is port security on a switch?",
    "a": "A feature that restricts which devices (by MAC address) can connect to a switch port, limiting the number of MACs and protecting against unauthorized devices and MAC flooding."
   }
  ]
 },
 {
  "id": "ch13",
  "num": 13,
  "title": "Chapter 13",
  "subtitle": "Wireless & Mobile Security",
  "emoji": "📶",
  "color": "#84cc16",
  "cards": [
   {
    "q": "Name common wireless connectivity types.",
    "a": "Wi-Fi (802.11), Cellular (4G/5G), Bluetooth (short-range device pairing), NFC (very short-range, e.g., tap payments), and GPS (location)."
   },
   {
    "q": "WPA2 vs. WPA3 — what's the key improvement?",
    "a": "WPA3 is the current standard. It replaces WPA2's PSK 4-way handshake with SAE (Simultaneous Authentication of Equals), protecting against offline password cracking and adding forward secrecy."
   },
   {
    "q": "What is WPA personal (PSK) vs. WPA enterprise?",
    "a": "Personal/PSK uses one shared pre-shared key for everyone. Enterprise uses 802.1X with a RADIUS server so each user authenticates with their own credentials (much more secure and manageable)."
   },
   {
    "q": "What is SAE?",
    "a": "Simultaneous Authentication of Equals — WPA3's secure handshake (a.k.a. Dragonfly) that resists offline dictionary attacks and provides forward secrecy, replacing WPA2's PSK handshake."
   },
   {
    "q": "Why should WEP never be used?",
    "a": "Wired Equivalent Privacy uses weak RC4 encryption and a flawed IV scheme that's trivially cracked in minutes — it's completely insecure and obsolete."
   },
   {
    "q": "What is EAP and name common variants?",
    "a": "Extensible Authentication Protocol — an authentication framework used with 802.1X. Variants include EAP-TLS (certificate-based, strongest), PEAP, EAP-TTLS, and EAP-FAST."
   },
   {
    "q": "What is an evil twin attack?",
    "a": "An attacker sets up a rogue access point that impersonates a legitimate Wi-Fi network (same SSID) to trick users into connecting so traffic can be intercepted."
   },
   {
    "q": "What is a rogue access point?",
    "a": "An unauthorized AP connected to a network (by an attacker or careless employee) that creates an insecure entry point bypassing network controls."
   },
   {
    "q": "What is a deauthentication (deauth) attack?",
    "a": "Sending forged deauth/disassociation frames to knock clients off a Wi-Fi network — used for denial of service or to force reconnection to an evil twin."
   },
   {
    "q": "Bluejacking vs. bluesnarfing?",
    "a": "Bluejacking sends unsolicited messages to a Bluetooth device (annoying but harmless). Bluesnarfing steals data from a Bluetooth device (a real breach)."
   },
   {
    "q": "What is a site survey and a heat map?",
    "a": "A site survey is a physical walkthrough using tools to map existing wireless signals, coverage, and interference. A heat map visually shows signal strength across the area to guide AP placement."
   },
   {
    "q": "Define the mobile deployment models BYOD, COPE, CYOD, and COBO.",
    "a": "BYOD = employees use personal devices. COPE = corporate-owned, personally enabled (some personal use allowed). CYOD = choose your own device from an approved list. COBO = corporate-owned, business only."
   },
   {
    "q": "What is MDM/UEM?",
    "a": "Mobile Device Management / Unified Endpoint Management — software to centrally configure, secure, monitor, and control mobile (and other) devices, including pushing apps and remote wiping."
   },
   {
    "q": "What is sideloading?",
    "a": "Installing apps from outside the official app store, bypassing its vetting — increasing the risk of installing malicious software."
   },
   {
    "q": "What is jailbreaking/rooting?",
    "a": "Removing manufacturer restrictions to gain root/admin access on a mobile device. It bypasses the built-in security model, creating significant security risk."
   },
   {
    "q": "What is containerization on mobile devices?",
    "a": "Separating corporate data/apps from personal data into an isolated, managed 'container' on the device so the company can secure/wipe work data without touching personal data."
   },
   {
    "q": "What is remote wipe?",
    "a": "An MDM capability to remotely erase data from a lost or stolen device (or just the corporate container) to prevent data exposure."
   },
   {
    "q": "What is geofencing?",
    "a": "Using GPS/location to define a virtual boundary and trigger policies (e.g., restrict access or disable features) based on whether a device is inside or outside an area."
   },
   {
    "q": "Why is public/open Wi-Fi a security risk for mobile users?",
    "a": "Traffic can be intercepted via on-path/evil-twin attacks. Users should use a VPN and HTTPS, and avoid sensitive transactions on untrusted networks."
   }
  ]
 },
 {
  "id": "ch14",
  "num": 14,
  "title": "Chapter 14",
  "subtitle": "Monitoring & Incident Response",
  "emoji": "🚨",
  "color": "#eab308",
  "cards": [
   {
    "q": "What are the phases of the incident response cycle (Security+)?",
    "a": "Preparation → Detection → Analysis → Containment → Eradication → Recovery → Lessons Learned. Phases can move forward or backward as new info emerges."
   },
   {
    "q": "What happens in the Preparation phase?",
    "a": "Building the capability to respond BEFORE an incident — policies, IR plan, tools, a trained team (CSIRT), communication plans, and exercises."
   },
   {
    "q": "Containment vs. eradication vs. recovery?",
    "a": "Containment = stop the spread/limit damage (isolate systems). Eradication = remove the threat (malware, attacker access). Recovery = restore systems to normal operation and verify they're clean."
   },
   {
    "q": "Why is the 'Lessons Learned' phase important?",
    "a": "After recovery, the team reviews what happened and how the response went to improve preparation, controls, and processes for the future."
   },
   {
    "q": "Name common incident response exercise types.",
    "a": "Tabletop exercises (discussion-based walkthrough of a scenario), walk-throughs, and simulations — practiced so teams can respond effectively under real pressure."
   },
   {
    "q": "What is a SIEM?",
    "a": "Security Information and Event Management — a system that aggregates logs/events from across the environment, correlates them, and provides dashboards, alerts, and analysis for detection and investigation."
   },
   {
    "q": "What is SOAR?",
    "a": "Security Orchestration, Automation, and Response — tools that automate and coordinate incident response workflows (playbooks), reducing manual effort and reaction time."
   },
   {
    "q": "What is the value of log aggregation/correlation?",
    "a": "Centralizing logs from many sources lets a SIEM correlate related events to reveal attacks that no single log would show on its own."
   },
   {
    "q": "What is 'impossible travel' as an IoC?",
    "a": "Logins from two geographically distant locations within a timeframe too short to physically travel between them — indicating compromised credentials."
   },
   {
    "q": "Name common indicators of compromise (IoCs) for incident detection.",
    "a": "Account lockouts, concurrent session usage, impossible travel, access to blocked content, unusual resource consumption, resource inaccessibility, out-of-cycle logging, and missing logs."
   },
   {
    "q": "What is NetFlow (and sFlow)?",
    "a": "Protocols that collect summary network traffic flow data — which systems talked, ports/protocols, volume, and timing — useful for bandwidth analysis and incident investigation."
   },
   {
    "q": "What is a packet analyzer/capture tool?",
    "a": "A tool (e.g., Wireshark, tcpdump) that captures and inspects raw network packets in detail — used to analyze traffic and investigate incidents."
   },
   {
    "q": "What is syslog?",
    "a": "A standard protocol/format for devices and systems to send log messages to a central logging server (often feeding a SIEM)."
   },
   {
    "q": "Why is metadata useful in incident response?",
    "a": "Metadata (timestamps, sender/recipient, file properties, geolocation) provides context about who did what, when, and where — often key evidence in investigations."
   },
   {
    "q": "Name common incident mitigation/containment techniques.",
    "a": "Isolation, containment, and segmentation of affected systems; using allow/block lists; quarantining files/devices; firewall and MDM/DLP changes; content/URL filtering; and revoking/updating certificates."
   },
   {
    "q": "What is root cause analysis?",
    "a": "Determining the underlying reason an incident occurred (not just the symptoms) so the organization can fix it and prevent recurrence."
   },
   {
    "q": "What is the difference between an event and an incident?",
    "a": "An event is any observable occurrence in a system/network. An incident is an event (or series) that actually violates or threatens security policy and requires response."
   },
   {
    "q": "What is quarantine in incident response?",
    "a": "Isolating a suspicious file or device (e.g., moving malware to a secure location, removing a host from the network) so it can't cause further harm while it's investigated."
   },
   {
    "q": "Why does log retention matter for IR and compliance?",
    "a": "Logs must be kept long enough to support investigations and meet legal/regulatory requirements — too-short retention can lose crucial evidence; storage and policy must balance both."
   }
  ]
 },
 {
  "id": "ch15",
  "num": 15,
  "title": "Chapter 15",
  "subtitle": "Digital Forensics",
  "emoji": "🔬",
  "color": "#d946ef",
  "cards": [
   {
    "q": "What is a legal hold?",
    "a": "A requirement to preserve and protect all information relevant to an active or anticipated legal case, preventing its alteration or destruction."
   },
   {
    "q": "What is e-discovery?",
    "a": "Electronic discovery — the process of identifying, collecting, and producing electronically stored information as evidence in response to a legal request."
   },
   {
    "q": "What is the order of volatility?",
    "a": "The sequence for collecting evidence from most to least volatile, so fragile data isn't lost: CPU registers/cache → RAM (memory) → network/temp data → disk → archived/backup media."
   },
   {
    "q": "Why collect the most volatile data first?",
    "a": "Volatile data (like RAM) is lost when a system loses power or changes state, while disk data persists — so capture what disappears fastest before it's gone."
   },
   {
    "q": "What is chain of custody?",
    "a": "Documentation that tracks who handled evidence, when, and why — from collection to court — proving it wasn't tampered with and keeping it admissible."
   },
   {
    "q": "What is a write blocker?",
    "a": "A hardware or software tool that allows reading from a drive while preventing any writes, so the original evidence stays unaltered during acquisition."
   },
   {
    "q": "What is a forensic (bit-by-bit) image?",
    "a": "An exact, sector-by-sector copy of a drive — including deleted files and slack space — so analysis is done on the copy while the original is preserved."
   },
   {
    "q": "Why hash forensic images, and which hashes are common?",
    "a": "Hashing creates a unique fingerprint; comparing hashes proves the copy matches the original and wasn't altered. MD5 and SHA-1 are still commonly used in forensics (no adversary is forging hashes there)."
   },
   {
    "q": "What is slack space?",
    "a": "Unused space within a disk cluster that may contain remnants of previously deleted files — often valuable forensic evidence captured by a full bit-by-bit image."
   },
   {
    "q": "How does forensic acquisition differ for VMs and cloud?",
    "a": "For VMs, use snapshots to capture state. For cloud, copy data volumes and rely on provider tools/APIs — acquisition depends on where the data lives and provider cooperation."
   },
   {
    "q": "What is provenance in digital forensics?",
    "a": "Documentation of the origin and complete history of evidence — where it came from and everything that happened to it — supporting authenticity."
   },
   {
    "q": "What is the difference between a checksum and a forensic hash?",
    "a": "A checksum verifies data hasn't changed (error detection). A cryptographic hash also produces a unique fingerprint used to authenticate forensic artifacts, not just detect accidental changes."
   },
   {
    "q": "What should a forensic report contain?",
    "a": "A summary of key findings; the process, tools, and procedures used; any limitations/assumptions; detailed findings with supporting evidence; and conclusions/recommendations."
   },
   {
    "q": "What is a right-to-audit clause?",
    "a": "A contractual provision allowing an organization to audit a vendor/partner's security controls and practices — important for managing third-party and forensic readiness."
   },
   {
    "q": "Why must forensic procedures be carefully documented and repeatable?",
    "a": "So evidence is admissible in court — another examiner following the same documented process should reach the same result, demonstrating reliability and integrity."
   },
   {
    "q": "What is data preservation in forensics?",
    "a": "Protecting evidence from any change after collection using chain-of-custody processes, write blockers, forensic copies, and documented handling procedures."
   }
  ]
 },
 {
  "id": "ch16",
  "num": 16,
  "title": "Chapter 16",
  "subtitle": "Security Governance & Compliance",
  "emoji": "📋",
  "color": "#22c55e",
  "cards": [
   {
    "q": "What is security governance?",
    "a": "The set of policies, procedures, and oversight (boards, committees, regulators) that direct and control an organization's security program to meet its strategic objectives."
   },
   {
    "q": "Centralized vs. decentralized governance?",
    "a": "Centralized uses a top-down approach where a central authority dictates how units meet security objectives. Decentralized delegates that authority to subordinate units to decide for themselves."
   },
   {
    "q": "Distinguish policies, standards, procedures, and guidelines.",
    "a": "Policies = high-level management intent (mandatory). Standards = specific mandatory requirements. Procedures = step-by-step instructions (mandatory). Guidelines = optional recommendations/advice."
   },
   {
    "q": "Which policy framework elements are mandatory vs. optional?",
    "a": "Policies, standards, and procedures are MANDATORY (compliance required). Guidelines are OPTIONAL advice that complements them."
   },
   {
    "q": "What is an Acceptable Use Policy (AUP)?",
    "a": "A policy defining how employees may use organizational systems, networks, and data — what's permitted and prohibited."
   },
   {
    "q": "Name common security policies.",
    "a": "Information security policy, AUP, data ownership policy, data retention policy, account management policy, password policy, and incident response policy."
   },
   {
    "q": "What is an exception process in a policy framework?",
    "a": "A defined procedure for requesting and approving exceptions to a security policy, including required justification, the approval authority, and compensating controls to mitigate the added risk."
   },
   {
    "q": "What is the primary goal of change management?",
    "a": "To ensure changes don't cause outages or security issues — by requiring review, approval, testing, and documentation before implementation."
   },
   {
    "q": "What elements are part of a good change management process?",
    "a": "Impact analysis, approval (often a Change Advisory Board), testing, documentation, a scheduled maintenance window, and a backout/rollback plan."
   },
   {
    "q": "What is a backout (rollback) plan?",
    "a": "A documented plan to reverse a change and restore the previous working state if the change fails or causes problems."
   },
   {
    "q": "What is PCI DSS?",
    "a": "Payment Card Industry Data Security Standard — a contractual standard that merchants and processors must follow to protect credit/debit cardholder data."
   },
   {
    "q": "What is GDPR?",
    "a": "EU General Data Protection Regulation — protects the personal data and privacy of EU residents, with strict requirements and large fines for non-compliance, regardless of where the company is located."
   },
   {
    "q": "What is HIPAA?",
    "a": "A U.S. law protecting the privacy and security of protected health information (PHI) handled by healthcare organizations and their partners."
   },
   {
    "q": "What are consequences of non-compliance?",
    "a": "Fines, legal sanctions/penalties, loss of certifications or business, contractual penalties, and reputational damage."
   },
   {
    "q": "What is the NIST Cybersecurity Framework (CSF)?",
    "a": "A voluntary framework for structuring a security program around core functions (Identify, Protect, Detect, Respond, Recover — plus Govern in CSF 2.0)."
   },
   {
    "q": "What is the NIST Risk Management Framework (RMF)?",
    "a": "A structured process (used by U.S. federal agencies/contractors) for managing security and privacy risk across the system life cycle through categorize/select/implement/assess/authorize/monitor steps."
   },
   {
    "q": "What is ISO 27001?",
    "a": "An international standard for establishing and maintaining an Information Security Management System (ISMS), often used as a certifiable framework."
   },
   {
    "q": "What is a maturity model?",
    "a": "A tool that lets an organization assess how developed/mature its security processes are and chart a path toward improvement."
   },
   {
    "q": "Distinguish data owner, controller, processor, and custodian/steward.",
    "a": "Owner = accountable for the data (usually a senior/business role). Controller = decides why/how data is processed. Processor = processes data on the controller's behalf. Custodian/steward = handles day-to-day protection and management."
   },
   {
    "q": "What is a DPO?",
    "a": "Data Protection Officer — a role (required under GDPR for some orgs) responsible for overseeing data protection strategy and regulatory compliance."
   },
   {
    "q": "What is vendor due diligence?",
    "a": "Investigating and assessing a vendor's security posture and practices before and during engagement, to reduce supply-chain/third-party risk."
   },
   {
    "q": "Distinguish SLA, MOU, MSA, BPA, and NDA.",
    "a": "SLA = service-level agreement (performance guarantees). MOU = memorandum of understanding (informal intent). MSA = master service agreement (overall terms). BPA = business partnership agreement. NDA = nondisclosure agreement (confidentiality)."
   },
   {
    "q": "Security training vs. security awareness?",
    "a": "Training imparts new knowledge/skills tailored to a role. Awareness reinforces and keeps existing security responsibilities top-of-mind (e.g., ongoing reminders, simulated phishing)."
   },
   {
    "q": "What is a data retention policy?",
    "a": "A policy defining how long different types of data must be kept and when it should be securely destroyed — balancing legal, regulatory, and business needs."
   }
  ]
 },
 {
  "id": "ch17",
  "num": 17,
  "title": "Chapter 17",
  "subtitle": "Risk Management & Privacy",
  "emoji": "⚖️",
  "color": "#38bdf8",
  "cards": [
   {
    "q": "What two factors define the level of a risk?",
    "a": "Likelihood/probability (how likely the risk is to occur) and impact/magnitude (how bad the effect would be if it does)."
   },
   {
    "q": "Qualitative vs. quantitative risk assessment?",
    "a": "Qualitative uses subjective ratings (high/medium/low). Quantitative assigns specific monetary/numeric values (e.g., dollar loss) to risks."
   },
   {
    "q": "What is a Business Impact Analysis (BIA)?",
    "a": "An analysis that identifies critical functions/assets and assesses the potential effects of disruptions, helping prioritize risks and recovery efforts (and set RTO/RPO)."
   },
   {
    "q": "What is the SLE formula?",
    "a": "Single Loss Expectancy = Asset Value (AV) × Exposure Factor (EF). It's the expected dollar loss from a single occurrence of a risk."
   },
   {
    "q": "What is the ALE formula?",
    "a": "Annualized Loss Expectancy = SLE × ARO (Annualized Rate of Occurrence). It's the expected total loss per year from a risk."
   },
   {
    "q": "What is the ARO?",
    "a": "Annualized Rate of Occurrence — how many times per year a risk is expected to occur (e.g., 0.5 = once every two years)."
   },
   {
    "q": "What are the four risk management strategies?",
    "a": "Avoidance (change practices to eliminate the risk), Mitigation (reduce likelihood/impact with controls), Transference (shift risk to a third party, e.g., insurance), and Acceptance (acknowledge and proceed)."
   },
   {
    "q": "When is risk acceptance appropriate?",
    "a": "When the cost of addressing the risk exceeds the potential loss, or the risk falls within the organization's risk appetite — it's formally acknowledged and documented."
   },
   {
    "q": "What is risk transference? Give an example.",
    "a": "Shifting some risk to a third party. The classic example is buying cybersecurity insurance, or outsourcing a risky function to a specialized provider."
   },
   {
    "q": "Inherent vs. residual risk?",
    "a": "Inherent risk is the risk before any controls are applied. Residual risk is what remains AFTER controls are implemented."
   },
   {
    "q": "What is risk appetite vs. risk tolerance/threshold?",
    "a": "Risk appetite is the overall amount of risk an organization is willing to accept to meet its goals. Risk tolerance/threshold is the specific acceptable variation/limit for a given risk."
   },
   {
    "q": "What is a risk register?",
    "a": "A documented list of identified risks with details like description, likelihood, impact, owner, and chosen response — used to track and manage risk over time."
   },
   {
    "q": "What is a KRI?",
    "a": "Key Risk Indicator — a metric that signals increasing risk exposure, used to monitor and provide early warning about risks."
   },
   {
    "q": "What is hardware source authenticity?",
    "a": "Verifying that hardware came from a legitimate source and wasn't tampered with (e.g., counterfeit or implanted) before reaching the organization — a supply-chain control."
   },
   {
    "q": "What is a disaster recovery (DR) plan?",
    "a": "A plan that activates after a natural or human-made disaster to quickly recover information and systems and resume normal operations."
   },
   {
    "q": "What is PII?",
    "a": "Personally Identifiable Information — data that can identify an individual (name, SSN, address, etc.), requiring protection from misuse and unauthorized disclosure."
   },
   {
    "q": "What is PHI?",
    "a": "Protected Health Information — individually identifiable health data, protected under HIPAA."
   },
   {
    "q": "What is the role of a data subject (vs. controller/processor) in privacy?",
    "a": "The data subject is the individual whom the personal data is about. The controller decides how it's used; the processor handles it for the controller."
   },
   {
    "q": "What is the 'right to be forgotten'?",
    "a": "A privacy right (notably under GDPR) allowing individuals to request that an organization delete their personal data."
   },
   {
    "q": "What is a Privacy Impact Assessment (PIA)?",
    "a": "An assessment that identifies and evaluates privacy risks of a system or process handling personal data, so they can be mitigated."
   },
   {
    "q": "Anonymization vs. pseudonymization?",
    "a": "Anonymization irreversibly removes identifying info so data can't be linked back to a person. Pseudonymization replaces identifiers with tokens that CAN be reversed with separate key data."
   },
   {
    "q": "What is third-party/vendor risk?",
    "a": "Risk introduced through external partners, suppliers, and service providers — managed via due diligence, contracts, right-to-audit clauses, and ongoing monitoring."
   }
  ]
 }
];
